"use client";
import {useCallback,useEffect,useState} from "react";
import type {ApiError} from "@/lib/products";
import {assetPayload,emptyAsset,toAssetInput,type Asset,type AssetInput,type AssetPage,type AssetType} from "@/lib/assets";

export function AssetsTab({productUuid,productArchived}:{productUuid:string;productArchived:boolean}){
 const [page,setPage]=useState<AssetPage|null>(null),[status,setStatus]=useState("ACTIVE"),[assetType,setAssetType]=useState(""),[pageNo,setPageNo]=useState(0);
 const [selected,setSelected]=useState<Asset|null>(null),[etag,setEtag]=useState<string|null>(null),[input,setInput]=useState<AssetInput>({...emptyAsset});
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[conflict,setConflict]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const q=new URLSearchParams({status,page:String(pageNo),size:"10",sort:"updatedAt,desc"});if(assetType)q.set("assetType",assetType);const r=await fetch(`/api/products/${productUuid}/assets?${q}`,{cache:"no-store"});const b=await r.json() as AssetPage&ApiError;if(!r.ok)throw new Error(b.message??"Unable to load assets");setPage(b);}catch(e){setError(e instanceof Error?e.message:"Unable to load assets");}finally{setLoading(false)}},[productUuid,status,assetType,pageNo]);
 useEffect(()=>{const controller=new AbortController();const q=new URLSearchParams({status,page:String(pageNo),size:"10",sort:"updatedAt,desc"});if(assetType)q.set("assetType",assetType);fetch(`/api/products/${productUuid}/assets?${q}`,{cache:"no-store",signal:controller.signal}).then(async r=>{const b=await r.json() as AssetPage&ApiError;if(!r.ok)throw new Error(b.message??"Unable to load assets");setPage(b)}).catch((e:unknown)=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Unable to load assets")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[productUuid,status,assetType,pageNo]);
 async function choose(asset:Asset){setConflict(false);setError(null);const r=await fetch(`/api/products/${productUuid}/assets/${asset.assetUuid}`,{cache:"no-store"});const b=await r.json() as Asset&ApiError;if(!r.ok){setError(b.message??"Unable to load asset");return}setSelected(b);setEtag(r.headers.get("ETag"));setInput(toAssetInput(b));}
 function fresh(){setSelected(null);setEtag(null);setInput({...emptyAsset});setConflict(false);setError(null);}
 async function save(){if(productArchived)return;setSaving(true);setError(null);setConflict(false);try{const creating=!selected;const body=assetPayload(input,creating);const url=creating?`/api/products/${productUuid}/assets`:`/api/products/${productUuid}/assets/${selected.assetUuid}`;const r=await fetch(url,{method:creating?"POST":"PATCH",headers:{"Content-Type":creating?"application/json":"application/merge-patch+json",...(!creating&&etag?{"If-Match":etag}:{})},body:JSON.stringify(body)});if([409,412,428].includes(r.status)){setConflict(true);return}const b=await r.json() as Asset&ApiError;if(!r.ok)throw new Error(b.message??"Unable to save asset");await load();await choose(b);}catch(e){setError(e instanceof Error?e.message:"Unable to save asset");}finally{setSaving(false)}}
 async function lifecycle(asset:Asset){if(productArchived)return;const latest=await fetch(`/api/products/${productUuid}/assets/${asset.assetUuid}`,{cache:"no-store"});const tag=latest.headers.get("ETag");if(!tag){setConflict(true);return}setSaving(true);const active=asset.lifecycleStatus==="ACTIVE";const r=await fetch(`/api/products/${productUuid}/assets/${asset.assetUuid}${active?"":"/restore"}`,{method:active?"DELETE":"POST",headers:{"If-Match":tag}});setSaving(false);if([409,412,428].includes(r.status)){setConflict(true);return}if(!r.ok){const b=await r.json() as ApiError;setError(b.message??"Unable to change asset lifecycle");return}fresh();await load();}
 const set=<K extends keyof AssetInput>(key:K,value:AssetInput[K])=>setInput(current=>({...current,[key]:value}));
 return <section className="content-card assets-tab">
  <div className="card-heading"><div><h2>Assets</h2><span className="summary">{page?.totalElements??0} records</span></div>{!productArchived&&<button className="primary-button" onClick={fresh}>New asset</button>}</div>
  {productArchived&&<div className="state-card warning-state">This product is archived. Asset metadata is read-only.</div>}
  <div className="creative-toolbar"><label>Status <select value={status} onChange={e=>{setStatus(e.target.value);setPageNo(0)}}><option>ACTIVE</option><option>ARCHIVED</option><option>ALL</option></select></label><label>Type <select value={assetType} onChange={e=>{setAssetType(e.target.value);setPageNo(0)}}><option value="">All types</option>{["IMAGE","VIDEO","DOCUMENT","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label></div>
  {loading?<div className="state-card" role="status">Loading assets...</div>:error&&!page?<div className="state-card error-state" role="alert">{error}</div>:page?.content.length===0?<div className="state-card">No assets found.</div>:<div className="creative-list">{page?.content.map(a=><article key={a.assetUuid} className="creative-item"><button className="creative-select" onClick={()=>void choose(a)}><strong>{a.originalFilename??a.purpose??a.assetType}</strong><span className={`status-badge ${a.lifecycleStatus.toLowerCase()}`}>{a.lifecycleStatus}</span></button>{a.fileUrl&&<a href={a.fileUrl} target="_blank" rel="noopener noreferrer">Open file</a>}{!productArchived&&<button className={a.lifecycleStatus==="ACTIVE"?"danger-button":"secondary-button"} disabled={saving} onClick={()=>void lifecycle(a)}>{a.lifecycleStatus==="ACTIVE"?"Archive":"Restore"}</button>}</article>)}</div>}
  {page&&<div className="pagination"><button disabled={pageNo===0} onClick={()=>setPageNo(v=>v-1)}>Previous</button><span>{pageNo+1} / {Math.max(page.totalPages,1)}</span><button disabled={pageNo+1>=page.totalPages} onClick={()=>setPageNo(v=>v+1)}>Next</button></div>}
  {conflict&&<div className="state-card warning-state" role="alert">The asset or one of its relationships changed. Reload before retrying. <button className="secondary-button" onClick={()=>{setConflict(false);void load()}}>Reload</button></div>}
  {error&&page&&<div className="state-card error-state" role="alert">{error}</div>}
  {!productArchived&&<form className="creative-form" onSubmit={e=>{e.preventDefault();void save()}}><h3>{selected?"Edit asset":"New asset metadata"}</h3><div className="form-grid">
   {!selected&&<><label>Creative Plan UUID<input value={input.creativePlanUuid} onChange={e=>set("creativePlanUuid",e.target.value)}/></label><label>Campaign UUID<input value={input.campaignUuid} onChange={e=>set("campaignUuid",e.target.value)}/></label></>}
   <label>Asset type<select required value={input.assetType} onChange={e=>set("assetType",e.target.value as AssetType)}>{["IMAGE","VIDEO","DOCUMENT","OTHER"].map(v=><option key={v}>{v}</option>)}</select></label>
   {(["purpose","storageProvider","providerFileId","fileUrl","mediaType","originalFilename","sizeBytes","checksumSha256"] as const).map(k=><label key={k}>{k}<input type={k==="sizeBytes"?"number":"text"} min={k==="sizeBytes"?0:undefined} value={input[k]} onChange={e=>set(k,e.target.value)}/></label>)}
   <label className="span-two">Provider metadata (JSON object)<textarea value={input.providerMetadata} onChange={e=>set("providerMetadata",e.target.value)}/></label>
  </div><button className="primary-button" disabled={saving}>{saving?"Saving...":"Save asset"}</button></form>}
 </section>;
}
