"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import type { Campaign, Page } from "@/lib/campaigns";
import type { ApiError } from "@/lib/products";

export function CampaignListView() {
  const router = useRouter(); const searchParams = useSearchParams(); const query = searchParams.toString();
  const [data, setData] = useState<Page<Campaign> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [conflict, setConflict] = useState(false); const [reload, setReload] = useState(0);
  useEffect(() => { const controller = new AbortController();
    fetch(`/api/campaigns${query ? `?${query}` : ""}`, { cache: "no-store", signal: controller.signal }).then(async response => { const body = await response.json() as Page<Campaign> & ApiError; if (!response.ok) throw new Error(body.message ?? "Campaign 載入失敗"); return body; }).then(setData).catch((failure: unknown) => { if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : "Campaign 載入失敗"); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort();
  }, [query, reload]);
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const next = new URLSearchParams(); for (const key of ["keyword", "status", "sort"]) { const value = form.get(key)?.toString().trim(); if (value) next.set(key, value); } next.set("page", "0"); next.set("size", searchParams.get("size") ?? "20"); router.push(`/campaigns?${next}`); }
  function page(number: number) { const next = new URLSearchParams(searchParams); next.set("page", String(number)); router.push(`/campaigns?${next}`); }
  async function lifecycle(item: Campaign) { setError(null); setConflict(false); const detail = await fetch(`/api/campaigns/${item.campaignUuid}`, { cache: "no-store" }); const etag = detail.headers.get("ETag"); if (!detail.ok || !etag) { setError("Campaign 最新版本載入失敗"); return; } const response = await fetch(item.lifecycleStatus === "ACTIVE" ? `/api/campaigns/${item.campaignUuid}` : `/api/campaigns/${item.campaignUuid}/restore`, { method: item.lifecycleStatus === "ACTIVE" ? "DELETE" : "POST", headers: { "If-Match": etag } }); if ([409, 412, 428].includes(response.status)) { setConflict(true); return; } if (!response.ok) { const failure = await response.json() as ApiError; setError(failure.message ?? "Campaign 狀態更新失敗"); return; } setLoading(true); setReload(value => value + 1); }
  return <div className="page-stack">
    <header className="page-header"><div><p className="eyebrow">Product Knowledge Center</p><h1>Campaigns</h1><p className="summary">管理 Campaign Plan 與商品關聯。</p></div><Link className="primary-button link-button" href="/campaigns/new">新增 Campaign</Link></header>
    <form className="filter-bar campaign-filter" onSubmit={filter}><input name="keyword" defaultValue={searchParams.get("keyword") ?? ""} placeholder="搜尋 Campaign" /><select name="status" defaultValue={searchParams.get("status") ?? "ACTIVE"}><option>ACTIVE</option><option>ARCHIVED</option><option>ALL</option></select><select name="sort" defaultValue={searchParams.get("sort") ?? "updatedAt,desc"}><option value="updatedAt,desc">最近更新</option><option value="campaignName,asc">名稱 A–Z</option><option value="startDate,asc">開始日期</option><option value="endDate,asc">結束日期</option></select><button className="secondary-button">套用</button></form>
    {conflict && <div className="state-card warning-state" role="alert">Campaign 已變更，請重新載入。<button className="secondary-button" onClick={() => { setConflict(false); setLoading(true); setReload(value => value + 1); }}>重新載入</button></div>}
    {loading ? <div className="state-card" role="status">載入 Campaigns…</div> : error ? <div className="state-card error-state" role="alert">{error}</div> : data?.content.length === 0 ? <div className="state-card">目前沒有 Campaign。</div> : <div className="table-shell"><table><thead><tr><th>Campaign</th><th>期間</th><th>平台</th><th>預算</th><th>狀態</th><th>操作</th></tr></thead><tbody>{data?.content.map(item => <tr key={item.campaignUuid}><td><Link href={`/campaigns/${item.campaignUuid}`}>{item.campaignName}</Link></td><td>{item.startDate ?? "—"} – {item.endDate ?? "—"}</td><td>{item.platform ?? "—"}</td><td>{item.budgetTotal ? `${item.currency ?? ""} ${item.budgetTotal}` : "—"}</td><td><span className={`status-badge ${item.lifecycleStatus.toLowerCase()}`}>{item.lifecycleStatus}</span></td><td><button className={item.lifecycleStatus === "ACTIVE" ? "danger-button" : "secondary-button"} onClick={() => void lifecycle(item)}>{item.lifecycleStatus === "ACTIVE" ? "封存" : "還原"}</button></td></tr>)}</tbody></table></div>}
    {data && <div className="pagination"><button className="secondary-button" disabled={data.page === 0} onClick={() => page(data.page - 1)}>上一頁</button><span>{data.page + 1} / {Math.max(data.totalPages, 1)}</span><button className="secondary-button" disabled={data.page + 1 >= data.totalPages} onClick={() => page(data.page + 1)}>下一頁</button></div>}
  </div>;
}
