"use client";

import { useCallback, useEffect, useState } from "react";
import { associationPatch, associationPayload, emptyAssociation, type AssociationInput, type CampaignProduct, type Page } from "@/lib/campaigns";
import type { ApiError, Product, ProductPage } from "@/lib/products";

export function CampaignProducts({ campaignUuid, campaignArchived }: { campaignUuid: string; campaignArchived: boolean }) {
  const [data, setData] = useState<Page<CampaignProduct> | null>(null); const [status, setStatus] = useState("ACTIVE"); const [page, setPage] = useState(0);
  const [input, setInput] = useState<AssociationInput>({ ...emptyAssociation }); const [selected, setSelected] = useState<CampaignProduct | null>(null); const [etag, setEtag] = useState<string | null>(null);
  const [products, setProducts] = useState<Product[]>([]); const [lookup, setLookup] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [conflict, setConflict] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch(`/api/campaigns/${campaignUuid}/products?status=${status}&page=${page}&size=10&sort=updatedAt,desc`, { cache: "no-store" }); const body = await response.json() as Page<CampaignProduct> & ApiError; if (!response.ok) throw new Error(body.message ?? "商品關聯載入失敗"); setData(body); } catch (failure) { setError(failure instanceof Error ? failure.message : "商品關聯載入失敗"); } finally { setLoading(false); } }, [campaignUuid, page, status]);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/campaigns/${campaignUuid}/products?status=${status}&page=${page}&size=10&sort=updatedAt,desc`, { cache: "no-store", signal: controller.signal }).then(async response => { const body = await response.json() as Page<CampaignProduct> & ApiError; if (!response.ok) throw new Error(body.message ?? "商品關聯載入失敗"); setData(body); }).catch((failure: unknown) => { if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : "商品關聯載入失敗"); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [campaignUuid, page, status]);
  async function searchProducts() { const response = await fetch(`/api/products?status=ACTIVE&page=0&size=20&keyword=${encodeURIComponent(lookup)}&sort=updatedAt,desc`, { cache: "no-store" }); const body = await response.json() as ProductPage & ApiError; if (!response.ok) { setError(body.message ?? "商品搜尋失敗"); return; } setProducts(body.content); }
  async function choose(item: CampaignProduct) { const response = await fetch(`/api/campaigns/${campaignUuid}/products/${item.productUuid}`, { cache: "no-store" }); const body = await response.json() as CampaignProduct & ApiError; if (!response.ok) { setError(body.message ?? "商品關聯載入失敗"); return; } setSelected(body); setEtag(response.headers.get("ETag")); setInput({ productUuid: body.productUuid, role: body.role ?? "", priority: body.priority == null ? "" : String(body.priority), budgetWeight: body.budgetWeight ?? "" }); setConflict(false); }
  function fresh() { setSelected(null); setEtag(null); setInput({ ...emptyAssociation }); setConflict(false); }
  async function save() { if (campaignArchived) return; const body = selected ? associationPatch(selected, input) : associationPayload(input); if (selected && Object.keys(body).length === 0) return; setSaving(true); setError(null); setConflict(false); const response = await fetch(selected ? `/api/campaigns/${campaignUuid}/products/${selected.productUuid}` : `/api/campaigns/${campaignUuid}/products`, { method: selected ? "PATCH" : "POST", headers: { "Content-Type": selected ? "application/merge-patch+json" : "application/json", ...(selected && etag ? { "If-Match": etag } : {}) }, body: JSON.stringify(body) }); setSaving(false); if ([409, 412, 428].includes(response.status)) { setConflict(true); return; } const result = await response.json() as CampaignProduct & ApiError; if (!response.ok) { setError(result.message ?? "商品關聯儲存失敗"); return; } fresh(); await load(); }
  async function lifecycle(item: CampaignProduct) { await choose(item); const response = await fetch(`/api/campaigns/${campaignUuid}/products/${item.productUuid}`, { cache: "no-store" }); const tag = response.headers.get("ETag"); if (!tag) { setConflict(true); return; } const changed = await fetch(item.lifecycleStatus === "ACTIVE" ? `/api/campaigns/${campaignUuid}/products/${item.productUuid}` : `/api/campaigns/${campaignUuid}/products/${item.productUuid}/restore`, { method: item.lifecycleStatus === "ACTIVE" ? "DELETE" : "POST", headers: { "If-Match": tag } }); if ([409, 412, 428].includes(changed.status)) { setConflict(true); return; } if (!changed.ok) { const body = await changed.json() as ApiError; setError(body.message ?? "關聯狀態更新失敗"); return; } fresh(); await load(); }
  return <section className="content-card campaign-products"><div className="card-heading"><div><h2>商品關聯</h2><span className="summary">{data?.totalElements ?? 0} 筆</span></div>{!campaignArchived && <button className="primary-button" onClick={fresh}>新增關聯</button>}</div>
    {campaignArchived && <div className="state-card warning-state">Archived Campaign 僅供閱讀；請先還原後再修改商品關聯。</div>}
    <div className="creative-toolbar"><label>狀態<select aria-label="關聯狀態" value={status} onChange={event => { setLoading(true); setStatus(event.target.value); setPage(0); }}><option>ACTIVE</option><option>ARCHIVED</option><option>ALL</option></select></label></div>
    {loading ? <div className="state-card" role="status">載入商品關聯…</div> : error && !data ? <div className="state-card error-state" role="alert">{error}</div> : data?.content.length === 0 ? <div className="state-card">目前沒有商品關聯。</div> : <div className="creative-list">{data?.content.map(item => <article className="creative-item" key={item.campaignProductUuid}><button className="creative-select" onClick={() => void choose(item)}><strong>{item.productUuid}</strong><span>{item.role ?? "—"} · {item.budgetWeight ?? "—"}%</span></button>{!campaignArchived && <button className={item.lifecycleStatus === "ACTIVE" ? "danger-button" : "secondary-button"} onClick={() => void lifecycle(item)}>{item.lifecycleStatus === "ACTIVE" ? "封存" : "還原"}</button>}</article>)}</div>}
    {data && <div className="pagination"><button disabled={page === 0} onClick={() => { setLoading(true); setPage(value => value - 1); }}>上一頁</button><span>{page + 1} / {Math.max(data.totalPages, 1)}</span><button disabled={page + 1 >= data.totalPages} onClick={() => { setLoading(true); setPage(value => value + 1); }}>下一頁</button></div>}
    {conflict && <div className="state-card warning-state" role="alert">資料已變更、關聯重複或資源目前不可修改。<button className="secondary-button" onClick={() => { setConflict(false); void load(); }}>重新載入</button></div>}
    {error && data && <div className="state-card error-state" role="alert">{error}</div>}
    {!campaignArchived && <form className="creative-form" onSubmit={event => { event.preventDefault(); void save(); }}><h3>{selected ? "編輯商品關聯" : "新增商品關聯"}</h3>{!selected && <div className="lookup-row"><input aria-label="商品搜尋" value={lookup} onChange={event => setLookup(event.target.value)} placeholder="搜尋 Product ID、SKU 或名稱" /><button type="button" className="secondary-button" onClick={() => void searchProducts()}>搜尋</button></div>}{!selected && products.length > 0 && <select aria-label="選擇商品" value={input.productUuid} onChange={event => setInput({ ...input, productUuid: event.target.value })}><option value="">選擇商品</option>{products.map(product => <option value={product.productUuid} key={product.productUuid}>{product.productId} · {product.productName}</option>)}</select>}<div className="form-grid"><label>Product UUID<input required disabled={Boolean(selected)} value={input.productUuid} onChange={event => setInput({ ...input, productUuid: event.target.value })} /></label><label>角色<input maxLength={128} value={input.role} onChange={event => setInput({ ...input, role: event.target.value })} /></label><label>優先順序<input type="number" min="0" value={input.priority} onChange={event => setInput({ ...input, priority: event.target.value })} /></label><label>預算權重 (%)<input type="number" min="0" max="100" step="0.01" value={input.budgetWeight} onChange={event => setInput({ ...input, budgetWeight: event.target.value })} /></label></div><button className="primary-button" disabled={saving}>{saving ? "儲存中…" : "儲存關聯"}</button></form>}
  </section>;
}
