"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { associationPatch, type AssociationInput, type Campaign, type CampaignProduct, type Page } from "@/lib/campaigns";
import type { ApiError } from "@/lib/products";

export function CampaignsTab({ productUuid, productArchived }: { productUuid: string; productArchived: boolean }) {
  const [data, setData] = useState<Page<Campaign> | null>(null); const [status, setStatus] = useState("ACTIVE"); const [page, setPage] = useState(0); const [campaignUuid, setCampaignUuid] = useState("");
  const [editing, setEditing] = useState<Campaign | null>(null); const [input, setInput] = useState<AssociationInput>({ productUuid, role: "", priority: "", budgetWeight: "" }); const [etag, setEtag] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [conflict, setConflict] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch(`/api/campaigns?productUuid=${productUuid}&associationStatus=${status}&status=ALL&page=${page}&size=10&sort=updatedAt,desc`, { cache: "no-store" }); const body = await response.json() as Page<Campaign> & ApiError; if (!response.ok) throw new Error(body.message ?? "Campaign 關聯載入失敗"); setData(body); } catch (failure) { setError(failure instanceof Error ? failure.message : "Campaign 關聯載入失敗"); } finally { setLoading(false); } }, [page, productUuid, status]);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/campaigns?productUuid=${productUuid}&associationStatus=${status}&status=ALL&page=${page}&size=10&sort=updatedAt,desc`, { cache: "no-store", signal: controller.signal }).then(async response => { const body = await response.json() as Page<Campaign> & ApiError; if (!response.ok) throw new Error(body.message ?? "Campaign 關聯載入失敗"); setData(body); }).catch((failure: unknown) => { if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : "Campaign 關聯載入失敗"); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [page, productUuid, status]);
  async function edit(item: Campaign) { if (!item.association) return; const response = await fetch(`/api/campaigns/${item.campaignUuid}/products/${productUuid}`, { cache: "no-store" }); const body = await response.json() as CampaignProduct & ApiError; if (!response.ok) { setError(body.message ?? "Campaign 關聯載入失敗"); return; } setEditing({ ...item, association: body }); setEtag(response.headers.get("ETag")); setInput({ productUuid, role: body.role ?? "", priority: body.priority == null ? "" : String(body.priority), budgetWeight: body.budgetWeight ?? "" }); }
  async function save() { const current = editing?.association; const body = current ? associationPatch(current, input) : { productUuid, role: input.role.trim() || null, priority: input.priority === "" ? null : Number(input.priority), budgetWeight: input.budgetWeight.trim() || null }; if (current && Object.keys(body).length === 0) return; const target = editing ? editing.campaignUuid : campaignUuid.trim(); const response = await fetch(`/api/campaigns/${target}/products${editing ? `/${productUuid}` : ""}`, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": editing ? "application/merge-patch+json" : "application/json", ...(editing && etag ? { "If-Match": etag } : {}) }, body: JSON.stringify(body) }); if ([409, 412, 428].includes(response.status)) { setConflict(true); return; } if (!response.ok) { const failure = await response.json() as ApiError; setError(failure.message ?? "Campaign 關聯儲存失敗"); return; } setEditing(null); setCampaignUuid(""); await load(); }
  async function lifecycle(item: Campaign) { const association = item.association; if (!association) return; const detail = await fetch(`/api/campaigns/${item.campaignUuid}/products/${productUuid}`, { cache: "no-store" }); const tag = detail.headers.get("ETag"); if (!tag) { setConflict(true); return; } const response = await fetch(association.lifecycleStatus === "ACTIVE" ? `/api/campaigns/${item.campaignUuid}/products/${productUuid}` : `/api/campaigns/${item.campaignUuid}/products/${productUuid}/restore`, { method: association.lifecycleStatus === "ACTIVE" ? "DELETE" : "POST", headers: { "If-Match": tag } }); if ([409, 412, 428].includes(response.status)) { setConflict(true); return; } if (!response.ok) { const failure = await response.json() as ApiError; setError(failure.message ?? "Campaign 關聯狀態更新失敗"); return; } await load(); }
  return <section className="content-card"><div className="card-heading"><div><h2>Campaigns</h2><span className="summary">{data?.totalElements ?? 0} 筆關聯</span></div></div>
    {productArchived && <div className="state-card warning-state">Archived Product 僅供閱讀；請先還原後再變更 Campaign 關聯。</div>}
    <div className="creative-toolbar"><label>關聯狀態<select aria-label="Campaign 關聯狀態" value={status} onChange={event => { setLoading(true); setStatus(event.target.value); setPage(0); }}><option>ACTIVE</option><option>ARCHIVED</option><option>ALL</option></select></label></div>
    {loading ? <div className="state-card" role="status">載入 Campaign 關聯…</div> : error && !data ? <div className="state-card error-state" role="alert">{error}</div> : data?.content.length === 0 ? <div className="state-card">此商品目前沒有 Campaign 關聯。</div> : <div className="creative-list">{data?.content.map(item => <article className="creative-item" key={item.campaignUuid}><div className="creative-select"><Link href={`/campaigns/${item.campaignUuid}`}><strong>{item.campaignName}</strong></Link><span>{item.association?.role ?? "—"} · {item.association?.budgetWeight ?? "—"}%</span></div>{!productArchived && item.lifecycleStatus === "ACTIVE" && <><button className="secondary-button" onClick={() => void edit(item)}>編輯</button><button className={item.association?.lifecycleStatus === "ACTIVE" ? "danger-button" : "secondary-button"} onClick={() => void lifecycle(item)}>{item.association?.lifecycleStatus === "ACTIVE" ? "封存" : "還原"}</button></>}</article>)}</div>}
    {data && <div className="pagination"><button disabled={page === 0} onClick={() => { setLoading(true); setPage(value => value - 1); }}>上一頁</button><span>{page + 1} / {Math.max(data.totalPages, 1)}</span><button disabled={page + 1 >= data.totalPages} onClick={() => { setLoading(true); setPage(value => value + 1); }}>下一頁</button></div>}
    {conflict && <div className="state-card warning-state" role="alert">Campaign 或關聯已變更，請重新載入。<button className="secondary-button" onClick={() => { setConflict(false); void load(); }}>重新載入</button></div>}{error && data && <div className="state-card error-state" role="alert">{error}</div>}
    {!productArchived && <form className="creative-form" onSubmit={event => { event.preventDefault(); void save(); }}><h3>{editing ? `編輯 ${editing.campaignName}` : "加入既有 Campaign"}</h3>{!editing && <label>Campaign UUID<input required value={campaignUuid} onChange={event => setCampaignUuid(event.target.value)} /></label>}<div className="form-grid"><label>角色<input maxLength={128} value={input.role} onChange={event => setInput({ ...input, role: event.target.value })} /></label><label>優先順序<input type="number" min="0" value={input.priority} onChange={event => setInput({ ...input, priority: event.target.value })} /></label><label>預算權重 (%)<input type="number" min="0" max="100" step="0.01" value={input.budgetWeight} onChange={event => setInput({ ...input, budgetWeight: event.target.value })} /></label></div><button className="primary-button">儲存關聯</button></form>}
  </section>;
}
