"use client";
import {useCallback,useEffect,useState} from "react";
import type {ApiError} from "@/lib/products";
import {creativePlanFields,emptyCreativePlan,patch,payload,toInput,type CreativePlan,type CreativePlanInput,type CreativePlanPage} from "@/lib/creative-plans";

const labels:Record<keyof CreativePlanInput,string>={planName:"計畫名稱",primaryAudience:"主要受眾",secondaryAudience:"次要受眾",painPoint:"痛點",coreBenefit:"核心利益",creativeAngle:"創意角度",emotionalDirection:"情緒方向",brandTone:"品牌語調",visualStyle:"視覺風格",mainColor:"主色",characterSetting:"角色設定",cta:"行動呼籲"};
export function CreativePlansTab({productUuid,productArchived}:{productUuid:string;productArchived:boolean}){
 const [page,setPage]=useState<CreativePlanPage|null>(null),[status,setStatus]=useState("ACTIVE"),[pageNo,setPageNo]=useState(0);
 const [selected,setSelected]=useState<CreativePlan|null>(null),[etag,setEtag]=useState<string|null>(null),[input,setInput]=useState<CreativePlanInput>(emptyCreativePlan);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[conflict,setConflict]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch(`/api/products/${productUuid}/creative-plans?status=${status}&page=${pageNo}&size=10&sort=updatedAt,desc`,{cache:"no-store"});const b=await r.json() as CreativePlanPage&ApiError;if(!r.ok)throw new Error(b.message??"創意計畫讀取失敗");setPage(b);}catch(e){setError(e instanceof Error?e.message:"創意計畫讀取失敗");}finally{setLoading(false)}},[productUuid,status,pageNo]);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/products/${productUuid}/creative-plans?status=${status}&page=${pageNo}&size=10&sort=updatedAt,desc`,{cache:"no-store",signal:controller.signal}).then(async r=>{const b=await r.json() as CreativePlanPage&ApiError;if(!r.ok)throw new Error(b.message??"創意計畫讀取失敗");setPage(b)}).catch((e:unknown)=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:"創意計畫讀取失敗")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[productUuid,status,pageNo]);
 async function choose(plan:CreativePlan){setError(null);setConflict(false);const r=await fetch(`/api/products/${productUuid}/creative-plans/${plan.creativePlanUuid}`,{cache:"no-store"});const b=await r.json() as CreativePlan&ApiError;if(!r.ok){setError(b.message??"創意計畫讀取失敗");return}setSelected(b);setEtag(r.headers.get("ETag"));setInput(toInput(b));}
 function fresh(){setSelected(null);setEtag(null);setInput({...emptyCreativePlan});setConflict(false);}
 async function save(){if(productArchived)return;setSaving(true);setError(null);setConflict(false);try{const url=selected?`/api/products/${productUuid}/creative-plans/${selected.creativePlanUuid}`:`/api/products/${productUuid}/creative-plans`;const body=selected?patch(toInput(selected),input):payload(input);if(selected&&Object.keys(body).length===0)return;const r=await fetch(url,{method:selected?"PATCH":"POST",headers:{"Content-Type":selected?"application/merge-patch+json":"application/json",...(selected&&etag?{"If-Match":etag}:{})},body:JSON.stringify(body)});if([409,412,428].includes(r.status)){setConflict(true);return}const b=await r.json() as CreativePlan&ApiError;if(!r.ok)throw new Error(b.message??"創意計畫儲存失敗");await load();await choose(b);}catch(e){setError(e instanceof Error?e.message:"創意計畫儲存失敗");}finally{setSaving(false)}}
 async function lifecycle(plan:CreativePlan){if(productArchived)return;await choose(plan);const latest=await fetch(`/api/products/${productUuid}/creative-plans/${plan.creativePlanUuid}`,{cache:"no-store"});const tag=latest.headers.get("ETag");if(!tag){setConflict(true);return}setSaving(true);const url=plan.lifecycleStatus==="ACTIVE"?`/api/products/${productUuid}/creative-plans/${plan.creativePlanUuid}`:`/api/products/${productUuid}/creative-plans/${plan.creativePlanUuid}/restore`;const r=await fetch(url,{method:plan.lifecycleStatus==="ACTIVE"?"DELETE":"POST",headers:{"If-Match":tag}});setSaving(false);if([409,412,428].includes(r.status)){setConflict(true);return}if(!r.ok){const b=await r.json() as ApiError;setError(b.message??"狀態變更失敗");return}fresh();await load();}
 return <section className="content-card creative-plans-tab">
  <div className="card-heading"><div><h2>Creative Plans</h2><span className="summary">{page?.totalElements??0} 筆</span></div>{!productArchived&&<button className="primary-button" onClick={fresh}>新增計畫</button>}</div>
  {productArchived&&<div className="state-card warning-state">商品已封存；Creative Plans 僅供讀取。</div>}
  <div className="creative-toolbar"><label>狀態<select value={status} onChange={e=>{setStatus(e.target.value);setPageNo(0)}}><option>ACTIVE</option><option>ARCHIVED</option><option>ALL</option></select></label></div>
  {loading?<div className="state-card" role="status">正在載入 Creative Plans…</div>:error&&!page?<div className="state-card error-state" role="alert">{error}</div>:page?.content.length===0?<div className="state-card">尚無 Creative Plan。</div>:<div className="creative-list">{page?.content.map(p=><article key={p.creativePlanUuid} className="creative-item"><button className="creative-select" onClick={()=>void choose(p)}><strong>{p.planName}</strong><span className={`status-badge ${p.lifecycleStatus.toLowerCase()}`}>{p.lifecycleStatus}</span></button>{!productArchived&&<button className={p.lifecycleStatus==="ACTIVE"?"danger-button":"secondary-button"} disabled={saving} onClick={()=>void lifecycle(p)}>{p.lifecycleStatus==="ACTIVE"?"封存":"還原"}</button>}</article>)}</div>}
  {page&&<div className="pagination"><button disabled={pageNo===0} onClick={()=>setPageNo(v=>v-1)}>上一頁</button><span>{pageNo+1} / {Math.max(page.totalPages,1)}</span><button disabled={pageNo+1>=page.totalPages} onClick={()=>setPageNo(v=>v+1)}>下一頁</button></div>}
  {conflict&&<div className="state-card warning-state" role="alert">資料狀態或版本已改變。<button className="secondary-button" onClick={()=>{setConflict(false);void load()}}>重新載入</button></div>}
  {error&&page&&<div className="state-card error-state" role="alert">{error}</div>}
  {!productArchived&&<form className="creative-form" onSubmit={e=>{e.preventDefault();void save()}}><h3>{selected?`編輯 ${selected.planName}`:"新增 Creative Plan"}</h3><div className="form-grid">{creativePlanFields.map((field,i)=><label key={field} className={i>1?"span-two":""}>{labels[field]}{field==="planName"?<input required maxLength={256} value={input[field]} onChange={e=>setInput({...input,[field]:e.target.value})}/>:<textarea maxLength={field==="mainColor"?128:field==="painPoint"||field==="coreBenefit"||field==="creativeAngle"?4000:field==="emotionalDirection"||field==="brandTone"||field==="cta"?1000:2000} value={input[field]} onChange={e=>setInput({...input,[field]:e.target.value})}/>}</label>)}</div><button className="primary-button" disabled={saving}>{saving?"儲存中…":"儲存計畫"}</button></form>}
 </section>;
}
