"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import type { ApiError } from "@/lib/products";
import { EMPTY_KNOWLEDGE, knowledgeInput, knowledgePatch } from "@/lib/knowledge";
import type { Knowledge, KnowledgeInput, KnowledgePage, KnowledgeType } from "@/lib/knowledge";
const TYPES: KnowledgeType[] = ["FEATURE","BENEFIT","AUDIENCE","PAIN_POINT","FAQ","PROOF","OTHER"];
export function KnowledgeTab({ productUuid, productArchived }: { productUuid: string; productArchived: boolean }) {
  const [items,setItems]=useState<Knowledge[]>([]); const [etags,setEtags]=useState<Record<string,string>>({});
  const [status,setStatus]=useState("ACTIVE"); const [sort,setSort]=useState("updatedAt,desc"); const [page,setPage]=useState(0); const [totalPages,setTotalPages]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const [editing,setEditing]=useState<Knowledge|null>(null); const [showForm,setShowForm]=useState(false); const [form,setForm]=useState<KnowledgeInput>(EMPTY_KNOWLEDGE); const [conflict,setConflict]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch(`/api/products/${productUuid}/knowledge?status=${status}&sort=${sort}&page=${page}&size=20`,{cache:"no-store"});const b=(await r.json()) as KnowledgePage & ApiError;if(!r.ok)throw new Error(b.message??"Unable to load knowledge");setItems(b.content);setTotalPages(b.totalPages);}catch(e){setError(e instanceof Error?e.message:"Unable to load knowledge");}finally{setLoading(false);}},[productUuid,status,sort,page]);
  useEffect(()=>{
    let active=true;
    fetch(`/api/products/${productUuid}/knowledge?status=${status}&sort=${sort}&page=${page}&size=20`,{cache:"no-store"})
      .then(async response=>{const body=(await response.json()) as KnowledgePage & ApiError;if(!response.ok)throw new Error(body.message??"Unable to load knowledge");if(active){setItems(body.content);setTotalPages(body.totalPages);}})
      .catch(failure=>{if(active)setError(failure instanceof Error?failure.message:"Unable to load knowledge");})
      .finally(()=>{if(active)setLoading(false);});
    return()=>{active=false;};
  },[productUuid,status,sort,page]);
  function startEdit(value?:Knowledge){setEditing(value??null);setShowForm(true);setForm(value?knowledgeInput(value):EMPTY_KNOWLEDGE);setConflict(false);}
  async function submit(e:FormEvent){e.preventDefault();if(productArchived)return;const url=editing?`/api/products/${productUuid}/knowledge/${editing.knowledgeUuid}`:`/api/products/${productUuid}/knowledge`;const body=editing?knowledgePatch(knowledgeInput(editing),form):{...form,source:form.source.trim()||null};if(editing&&Object.keys(body).length===0)return;const r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"Content-Type":editing?"application/merge-patch+json":"application/json",...(editing?{"If-Match":etags[editing.knowledgeUuid]??`W/"${editing.version}"`}:{})},body:JSON.stringify(body)});if([409,412,428].includes(r.status)){setConflict(true);return;}const b=(await r.json()) as Knowledge & ApiError;if(!r.ok){setError(b.message??"Unable to save knowledge");return;}setEtags(v=>({...v,[b.knowledgeUuid]:r.headers.get("ETag")??`W/"${b.version}"`}));setEditing(null);setShowForm(false);setForm(EMPTY_KNOWLEDGE);await load();}
  async function lifecycle(value:Knowledge){if(productArchived)return;const restore=value.lifecycleStatus==="ARCHIVED";const r=await fetch(`/api/products/${productUuid}/knowledge/${value.knowledgeUuid}${restore?"/restore":""}`,{method:restore?"POST":"DELETE",headers:{"If-Match":etags[value.knowledgeUuid]??`W/"${value.version}"`}});if([409,412,428].includes(r.status)){setConflict(true);return;}if(!r.ok){const b=await r.json() as ApiError;setError(b.message??"Unable to update knowledge");return;}await load();}
  return <section className="content-card" aria-labelledby="knowledge-heading"><div className="card-heading"><div><h2 id="knowledge-heading">Product Knowledge</h2><span className="status-badge active">{items.length}</span></div>{!productArchived&&<button className="primary-button" onClick={()=>startEdit()}>Add knowledge</button>}</div>
    {productArchived&&<div className="state-card warning-state">This product is archived. Knowledge remains readable but cannot be changed.</div>}
    <div className="knowledge-filters"><label className="knowledge-filter">Status <select value={status} onChange={e=>{setLoading(true);setError(null);setStatus(e.target.value);setPage(0);}}><option>ACTIVE</option><option>ARCHIVED</option><option>ALL</option></select></label><label className="knowledge-filter">Sort <select value={sort} onChange={e=>{setLoading(true);setError(null);setSort(e.target.value);setPage(0);}}><option value="updatedAt,desc">Recently updated</option><option value="createdAt,asc">Oldest created</option><option value="title,asc">Title A–Z</option><option value="knowledgeType,asc">Type A–Z</option></select></label></div>
    {conflict&&<div role="alert" className="state-card warning-state">Knowledge changed or is no longer editable. <button className="secondary-button" onClick={()=>window.location.reload()}>Reload latest product</button></div>}
    {error&&<div role="alert" className="state-card error-state">{error}</div>}{loading?<div role="status" className="state-card">Loading knowledge…</div>:items.length===0?<div className="state-card">No knowledge entries.</div>:<><div className="knowledge-list">{items.map(value=><article className="knowledge-card" key={value.knowledgeUuid}><div><span className={`status-badge ${value.lifecycleStatus.toLowerCase()}`}>{value.knowledgeType} · {value.lifecycleStatus}</span><h3>{value.title}</h3><p>{value.content}</p>{value.source&&<small>{value.source}</small>}</div>{!productArchived&&<div className="knowledge-actions">{value.lifecycleStatus==="ACTIVE"&&<button className="secondary-button" onClick={()=>startEdit(value)}>Edit</button>}<button className={value.lifecycleStatus==="ACTIVE"?"danger-button":"secondary-button"} onClick={()=>void lifecycle(value)}>{value.lifecycleStatus==="ACTIVE"?"Archive":"Restore"}</button></div>}</article>)}</div><div className="pagination"><button className="secondary-button" disabled={page===0} onClick={()=>{setLoading(true);setPage(v=>v-1);}}>Previous</button><span>Page {page+1} of {Math.max(totalPages,1)}</span><button className="secondary-button" disabled={page+1>=totalPages} onClick={()=>{setLoading(true);setPage(v=>v+1);}}>Next</button></div></>}
    {!productArchived&&showForm&&<form className="product-form knowledge-form" onSubmit={submit}><h3>{editing?"Edit knowledge":"New knowledge"}</h3><label>Type<select value={form.knowledgeType} onChange={e=>setForm(v=>({...v,knowledgeType:e.target.value as KnowledgeType}))}>{TYPES.map(v=><option key={v}>{v}</option>)}</select></label><label>Title<input required maxLength={256} value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></label><label>Content<textarea required maxLength={20000} rows={6} value={form.content} onChange={e=>setForm(v=>({...v,content:e.target.value}))}/></label><label>Source<input maxLength={2048} value={form.source} onChange={e=>setForm(v=>({...v,source:e.target.value}))}/></label><div className="knowledge-actions"><button className="primary-button">Save knowledge</button><button type="button" className="secondary-button" onClick={()=>{setEditing(null);setShowForm(false);setForm(EMPTY_KNOWLEDGE);}}>Cancel</button></div></form>}
  </section>;
}
