import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { KnowledgeTab } from "./knowledge-tab";
const entry={knowledgeUuid:"5cf53b23-eabe-4b51-b565-62dbe4333721",productUuid:"d4476a19-30ed-48d9-a518-f9b111bd0911",knowledgeType:"FEATURE",title:"Feature title",content:"Feature content",source:null,lifecycleStatus:"ACTIVE",archivedAt:null,createdAt:"2026-08-07T00:00:00Z",updatedAt:"2026-08-07T00:00:00Z",version:0};
describe("KnowledgeTab",()=>{afterEach(()=>{cleanup();vi.unstubAllGlobals();});
 it("loads, creates, edits and archives knowledge through same-origin endpoints",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({content:[entry],page:0,size:20,totalElements:1,totalPages:1}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({...entry,title:"New"}),{status:201,headers:{ETag:'W/"0"'}})).mockResolvedValueOnce(new Response(JSON.stringify({content:[entry],page:0,size:20,totalElements:1,totalPages:1}),{status:200})).mockResolvedValueOnce(new Response(null,{status:204})).mockResolvedValueOnce(new Response(JSON.stringify({content:[],page:0,size:20,totalElements:0,totalPages:0}),{status:200}));vi.stubGlobal("fetch",fetchMock);render(<KnowledgeTab productUuid={entry.productUuid} productArchived={false}/>);await screen.findByText("Feature title");fireEvent.click(screen.getByRole("button",{name:"Add knowledge"}));fireEvent.change(screen.getByLabelText("Title"),{target:{value:"New"}});fireEvent.change(screen.getByLabelText("Content"),{target:{value:"Body"}});fireEvent.click(screen.getByRole("button",{name:"Save knowledge"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(3));fireEvent.click(screen.getByRole("button",{name:"Archive"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(5));expect(fetchMock.mock.calls[1][0]).toBe(`/api/products/${entry.productUuid}/knowledge`);expect(fetchMock.mock.calls[3][1]).toEqual(expect.objectContaining({method:"DELETE",headers:{"If-Match":'W/"0"'}}));});
 it("is read-only for an archived product",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(JSON.stringify({content:[entry],page:0,size:20,totalElements:1,totalPages:1}),{status:200})));render(<KnowledgeTab productUuid={entry.productUuid} productArchived/>);await screen.findByText("Feature title");expect(screen.getByText(/remains readable/)).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Add knowledge"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Archive"})).not.toBeInTheDocument();});
 it.each([409,412,428])("offers reload on concurrency status %s",async(status)=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({content:[entry],page:0,size:20,totalElements:1,totalPages:1}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({code:"PRECONDITION_FAILED"}),{status}));vi.stubGlobal("fetch",fetchMock);render(<KnowledgeTab productUuid={entry.productUuid} productArchived={false}/>);await screen.findByText("Feature title");fireEvent.click(screen.getByRole("button",{name:"Archive"}));expect(await screen.findByRole("alert")).toHaveTextContent("changed or is no longer editable");});
});
