"use client";

import { FormEvent, useState } from "react";
import type { PlatformOperationView } from "@/lib/platform-stage4b";

type Preview={clientRequestUuid:string;operationType:string;entityType:string;entityUuid?:string;desiredState:string;budgetType?:string;budgetAmount?:string;reservation:{kind:string;reservedDelta:string;accountDayRemainingAfter:string};policy:{currency:string};warnings:string[];expectedCampaignPlanVersion?:number;expectedEntityVersion?:number};
type AdPreview={clientRequestUuid:string;platformAdSetUuid:string;expectedParentVersion:number;productUuid:string;assetUuid:string;generationOutputUuid:string;reviewDecisionUuid:string;approvedChecksumFingerprint:string;creativeMappingKey:string;parentCampaignDesiredState:string;parentAdSetDesiredState:string;newAdDesiredState:string;evidenceEligible:boolean;warnings:string[];confirmable:boolean};
type AdStatePreview={clientRequestUuid:string;entityType:"AD";entityUuid:string;expectedEntityVersion:number;previousDesiredState:string;targetDesiredState:string;parentCampaignDesiredState:string;parentAdSetDesiredState:string;evidenceEligible:boolean;warnings:string[];confirmable:boolean};
type EntityView={version:number;desiredState:string;budgetAmount?:string};
type AdView={platformAdUuid:string;desiredState:string;version:number;creativeMappingKey:string;approvedChecksumFingerprint:string};
const uuid=()=>crypto.randomUUID();

export function PlatformMetaManager({stage4c=false}:{stage4c?:boolean}){
 const [campaignPlan,setCampaignPlan]=useState("");const [campaign,setCampaign]=useState("");const [campaignEtag,setCampaignEtag]=useState("");const [campaignView,setCampaignView]=useState<EntityView|null>(null);
 const [adSet,setAdSet]=useState("");const [adSetEtag,setAdSetEtag]=useState("");const [adSetView,setAdSetView]=useState<EntityView|null>(null);const [budget,setBudget]=useState("50");
 const [preview,setPreview]=useState<Preview|null>(null);const [operation,setOperation]=useState<PlatformOperationView|null>(null);const [operationEtag,setOperationEtag]=useState("");const [error,setError]=useState("");
 const [retryEligible,setRetryEligible]=useState(false);
 const [pendingAction,setPendingAction]=useState<"retry"|"reconcile"|null>(null);
 const [productUuid,setProductUuid]=useState("");const [assetUuid,setAssetUuid]=useState("");const [outputUuid,setOutputUuid]=useState("");const [reviewUuid,setReviewUuid]=useState("");
 const [ad,setAd]=useState("");const [adEtag,setAdEtag]=useState("");const [adView,setAdView]=useState<AdView|null>(null);
 const [adPreview,setAdPreview]=useState<AdPreview|null>(null);const [adStatePreview,setAdStatePreview]=useState<AdStatePreview|null>(null);
 async function call(path:string,body?:unknown,etag?:string){setError("");const headers:Record<string,string>={};if(body)headers["Content-Type"]="application/json";if(etag)headers["If-Match"]=etag;const response=await fetch(path,{method:body?"POST":"GET",headers,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok){setError(data.message??"Request failed");const failure=new Error(data.code??"REQUEST_FAILED");Object.assign(failure,{status:response.status});throw failure;}return {data,response};}
 async function loadCampaign(id=campaign){if(!id)return;const {data,response}=await call(`/api/platforms/meta/campaigns/${id}`);setCampaignView(data);setCampaignEtag(response.headers.get("etag")??"");}
 async function loadAdSet(id=adSet){if(!id)return;const {data,response}=await call(`/api/platforms/meta/ad-sets/${id}`);setAdSetView(data);setAdSetEtag(response.headers.get("etag")??"");}
 async function loadAd(id=ad){if(!id)return;const {data,response}=await call(`/api/platforms/meta/ads/${id}`);setAdView(data);setAdEtag(response.headers.get("etag")??"");setAd(id);}
 function applyOperation(value:PlatformOperationView){setOperation(value);setRetryEligible(value.status==="FAILED_RETRYABLE"&&!!value.nextAttemptAt&&Date.parse(value.nextAttemptAt)<=Date.now());}
 async function loadOperation(){if(!operation)return;const {data,response}=await call(`/api/platform-operations/${operation.operationUuid}`);applyOperation(data);setOperationEtag(response.headers.get("etag")??"");}
 async function campaignPreview(e:FormEvent){e.preventDefault();const {data}=await call("/api/platforms/meta/campaigns/preview",{clientRequestUuid:uuid(),campaignUuid:campaignPlan});setPreview(data);setAdPreview(null);setAdStatePreview(null);}
 async function confirmCampaign(){if(!preview)return;const {data,response}=await call("/api/platforms/meta/campaigns",{clientRequestUuid:preview.clientRequestUuid,campaignUuid:campaignPlan,expectedCampaignPlanVersion:preview.expectedCampaignPlanVersion});applyOperation(data);setOperationEtag(response.headers.get("etag")??"");setCampaign(data.entityUuid);await loadCampaign(data.entityUuid);setPreview(null);}
 async function adSetPreview(e:FormEvent){e.preventDefault();const {data}=await call(`/api/platforms/meta/campaigns/${campaign}/ad-sets/preview`,{clientRequestUuid:uuid(),budgetType:"DAILY",budgetAmount:budget});setPreview(data);setAdPreview(null);setAdStatePreview(null);}
 async function confirmAdSet(){if(!preview)return;try{const {data,response}=await call(`/api/platforms/meta/campaigns/${campaign}/ad-sets`,{clientRequestUuid:preview.clientRequestUuid,budgetType:"DAILY",budgetAmount:budget,expectedCampaignPlanVersion:preview.expectedCampaignPlanVersion},campaignEtag);applyOperation(data);setOperationEtag(response.headers.get("etag")??"");setAdSet(data.entityUuid);await loadAdSet(data.entityUuid);setPreview(null);}catch(failure){if((failure as {status?:number}).status===412){setPreview(null);setPendingAction(null);await loadCampaign();}}}
 async function statePreview(type:"campaigns"|"ad-sets",id:string,target:"PAUSED"|"ACTIVE"){const {data}=await call(`/api/platforms/meta/${type}/${id}/state-preview`,{clientRequestUuid:uuid(),targetDesiredState:target});setPreview(data);setAdPreview(null);setAdStatePreview(null);}
 async function confirmState(){if(!preview?.entityUuid)return;const campaigns=preview.entityType==="CAMPAIGN";const type=campaigns?"campaigns":"ad-sets";const action=preview.desiredState==="ACTIVE"?"resume":"pause";try{const {data,response}=await call(`/api/platforms/meta/${type}/${preview.entityUuid}/${action}`,{clientRequestUuid:preview.clientRequestUuid,targetDesiredState:preview.desiredState},campaigns?campaignEtag:adSetEtag);applyOperation(data);setOperationEtag(response.headers.get("etag")??"");await(campaigns?loadCampaign():loadAdSet());setPreview(null);}catch(failure){if((failure as {status?:number}).status===412){setPreview(null);setPendingAction(null);await(campaigns?loadCampaign():loadAdSet());}}}
 async function budgetPreview(e:FormEvent){e.preventDefault();const {data}=await call(`/api/platforms/meta/ad-sets/${adSet}/budget-preview`,{clientRequestUuid:uuid(),newBudgetAmount:budget});setPreview(data);setAdPreview(null);setAdStatePreview(null);}
 async function confirmBudget(){if(!preview)return;try{const {data,response}=await call(`/api/platforms/meta/ad-sets/${adSet}/budget`,{clientRequestUuid:preview.clientRequestUuid,newBudgetAmount:budget},adSetEtag);applyOperation(data);setOperationEtag(response.headers.get("etag")??"");await loadAdSet();setPreview(null);}catch(failure){if((failure as {status?:number}).status===412){setPreview(null);setPendingAction(null);await loadAdSet();}}}
 async function adCreatePreview(e:FormEvent){e.preventDefault();const {data}=await call(`/api/platforms/meta/ad-sets/${adSet}/ads/preview`,{clientRequestUuid:uuid(),productUuid,assetUuid,generationOutputUuid:outputUuid,reviewDecisionUuid:reviewUuid},adSetEtag);setAdPreview(data);setPreview(null);setAdStatePreview(null);}
 async function confirmAdCreate(){if(!adPreview)return;try{const {data,response}=await call(`/api/platforms/meta/ad-sets/${adSet}/ads`,{clientRequestUuid:adPreview.clientRequestUuid,productUuid,assetUuid,generationOutputUuid:outputUuid,reviewDecisionUuid:reviewUuid},adSetEtag);applyOperation(data);setOperationEtag(response.headers.get("etag")??"");setAd(data.entityUuid);await loadAd(data.entityUuid);setAdPreview(null);}catch(failure){if((failure as {status?:number}).status===412){setAdPreview(null);setPendingAction(null);await loadAdSet();}}}
 async function previewAdState(target:"PAUSED"|"ACTIVE"){const {data}=await call(`/api/platforms/meta/ads/${ad}/state/preview`,{clientRequestUuid:uuid(),targetDesiredState:target},adEtag);setAdStatePreview(data);setPreview(null);setAdPreview(null);}
 async function confirmAdState(){if(!adStatePreview)return;const action=adStatePreview.targetDesiredState==="ACTIVE"?"resume":"pause";try{const {data,response}=await call(`/api/platforms/meta/ads/${ad}/${action}`,{clientRequestUuid:adStatePreview.clientRequestUuid,targetDesiredState:adStatePreview.targetDesiredState},adEtag);applyOperation(data);setOperationEtag(response.headers.get("etag")??"");await loadAd();setAdStatePreview(null);}catch(failure){if((failure as {status?:number}).status===412){setAdStatePreview(null);setPendingAction(null);await loadAd();}}}
 async function operationAction(action:"retry"|"reconcile"){if(!operation)return;setError("");const response=await fetch(`/api/platform-operations/${operation.operationUuid}/${action}`,{method:"POST",headers:{"If-Match":operationEtag}});const data=await response.json();setPendingAction(null);if(!response.ok){setError(data.message??"Request failed");if(response.status===412)await loadOperation();return;}applyOperation(data);setOperationEtag(response.headers.get("etag")??"");}
 const confirm=preview?.operationType==="CREATE_CAMPAIGN"?confirmCampaign:preview?.operationType==="CREATE_AD_SET"?confirmAdSet:preview?.operationType==="UPDATE_BUDGET"?confirmBudget:confirmState;
 return <main className="page-shell"><header className="page-header"><div><p className="eyebrow">Deterministic FAKE · Local/Test</p><h1>Meta platform operations</h1><p>Preview and explicitly confirm each FAKE mutation.</p></div></header>
  {error&&<div className="error-banner" role="alert">{error}</div>}
  <section className="panel"><h2>1. Campaign</h2><form onSubmit={campaignPreview}><label>Campaign Plan UUID<input value={campaignPlan} onChange={e=>setCampaignPlan(e.target.value)} required /></label><button type="submit">Preview paused Campaign</button></form><label>Platform Campaign UUID<input value={campaign} onChange={e=>setCampaign(e.target.value)} /></label><button type="button" onClick={()=>loadCampaign()}>Load Campaign</button>{campaignView&&<EntityStatus label="Campaign" value={campaignView}/>} {campaignView&&<button type="button" onClick={()=>statePreview("campaigns",campaign,campaignView.desiredState==="ACTIVE"?"PAUSED":"ACTIVE")}>Preview {campaignView.desiredState==="ACTIVE"?"pause":"resume"} Campaign</button>}</section>
  <section className="panel"><h2>2. Ad Set</h2><form onSubmit={adSetPreview}><label>Daily budget (TWD)<input value={budget} onChange={e=>setBudget(e.target.value)} inputMode="decimal" required /></label><button type="submit">Preview paused Ad Set</button></form><label>Platform Ad Set UUID<input value={adSet} onChange={e=>setAdSet(e.target.value)} /></label><button type="button" onClick={()=>loadAdSet()}>Load Ad Set</button>{adSetView&&<EntityStatus label="Ad Set" value={adSetView}/>} {adSetView&&<><button type="button" onClick={()=>statePreview("ad-sets",adSet,adSetView.desiredState==="ACTIVE"?"PAUSED":"ACTIVE")}>Preview {adSetView.desiredState==="ACTIVE"?"pause":"resume"} Ad Set</button><form onSubmit={budgetPreview}><button type="submit">Preview budget change</button></form></>}</section>
  {stage4c&&<section className="panel"><h2>3. Ad</h2><p role="note">Create and resume revalidate the current approved IMAGE evidence chain. History is preserved if that chain later diverges; create and resume then stay blocked. Pause remains available. FAKE mode never delivers or spends.</p><form onSubmit={adCreatePreview}><label>Product UUID<input value={productUuid} onChange={e=>setProductUuid(e.target.value)} required /></label><label>Asset UUID<input value={assetUuid} onChange={e=>setAssetUuid(e.target.value)} required /></label><label>Generation output UUID<input value={outputUuid} onChange={e=>setOutputUuid(e.target.value)} required /></label><label>Review decision UUID<input value={reviewUuid} onChange={e=>setReviewUuid(e.target.value)} required /></label><button type="submit">Preview paused Ad</button></form><label>Platform Ad UUID<input value={ad} onChange={e=>setAd(e.target.value)} /></label><button type="button" onClick={()=>loadAd()}>Load Ad</button>{adView&&<dl aria-label="Ad status"><dt>Desired state</dt><dd>{adView.desiredState}</dd><dt>Mapping</dt><dd>{adView.creativeMappingKey}</dd><dt>Checksum fingerprint</dt><dd>{adView.approvedChecksumFingerprint}</dd></dl>}{adView&&<button type="button" onClick={()=>previewAdState(adView.desiredState==="ACTIVE"?"PAUSED":"ACTIVE")}>Preview {adView.desiredState==="ACTIVE"?"pause":"resume"} Ad</button>}</section>}
  {preview&&<Confirmation preview={preview} onConfirm={confirm}/>}
  {adPreview&&<AdConfirmation preview={adPreview} onConfirm={confirmAdCreate}/>}
  {adStatePreview&&<AdStateConfirmation preview={adStatePreview} onConfirm={confirmAdState}/>}
  {operation&&<section className="panel" aria-live="polite"><h2>Operation status</h2><dl><dt>Operation</dt><dd>{operation.operationUuid}</dd><dt>Entity</dt><dd>{operation.entityUuid}</dd><dt>Status</dt><dd><strong>{operation.status}</strong></dd><dt>Attempts</dt><dd>{operation.attemptCount} / {operation.maxAttempts}</dd></dl><button type="button" onClick={loadOperation}>Refresh operation</button>{retryEligible&&<button type="button" onClick={()=>setPendingAction("retry")}>Retry due operation</button>}{operation.status==="FAILED_RETRYABLE"&&!retryEligible&&<p>Retry becomes available at {operation.nextAttemptAt??"the server-provided due time"}.</p>}{operation.status==="UNKNOWN_OUTCOME"&&<><p role="alert">Outcome is unknown. Reconcile before any retry.</p><button type="button" onClick={()=>setPendingAction("reconcile")}>Reconcile unknown outcome</button></>}</section>}
  {pendingAction&&<section className="confirmation-card" role="dialog" aria-label={`Confirm ${pendingAction}`}><h3>Explicit confirmation required</h3><p>{pendingAction==="retry"?"Retry only the due persisted operation; no automatic retry occurs.":"Reconcile the unknown persisted operation; do not create a replacement."}</p><p>FAKE mode never delivers or spends.</p><button type="button" onClick={()=>operationAction(pendingAction)}>Confirm {pendingAction}</button><button type="button" onClick={()=>setPendingAction(null)}>Cancel</button></section>}
 </main>;
}
function EntityStatus({label,value}:{label:string,value:EntityView}){return <dl aria-label={`${label} status`}><dt>Desired state</dt><dd>{value.desiredState}</dd><dt>Version</dt><dd>{value.version}</dd>{value.budgetAmount&&<><dt>Budget</dt><dd>{value.budgetAmount}</dd></>}</dl>}
function Confirmation({preview,onConfirm}:{preview:Preview,onConfirm:()=>void}){return <section className="confirmation-card" role="dialog" aria-label="Confirm platform mutation"><h3>Explicit confirmation required</h3><p>Desired state: <strong>{preview.desiredState}</strong></p><p>Authorization: {preview.policy.currency} {preview.reservation.reservedDelta}; remaining today {preview.reservation.accountDayRemainingAfter}</p>{preview.warnings.includes("CAPACITY_NOT_RELEASED")&&<p role="alert">This decrease does not release previously authorized capacity.</p>}<p>Confirmation revalidates versions and policy. FAKE mode never delivers or spends.</p><button type="button" onClick={onConfirm}>Confirm FAKE operation</button></section>}
function AdConfirmation({preview,onConfirm}:{preview:AdPreview,onConfirm:()=>void}){return <section className="confirmation-card" role="dialog" aria-label="Confirm Ad publication"><h3>Explicit confirmation required</h3><p>Mapping: <strong>{preview.creativeMappingKey}</strong></p><p>New Ad state: <strong>{preview.newAdDesiredState}</strong></p><p>Checksum fingerprint: {preview.approvedChecksumFingerprint}</p><p>FAKE only. No real provider or spend. Evidence divergence blocks create or resume.</p><button type="button" onClick={onConfirm}>Confirm FAKE operation</button></section>}
function AdStateConfirmation({preview,onConfirm}:{preview:AdStatePreview,onConfirm:()=>void}){return <section className="confirmation-card" role="dialog" aria-label="Confirm Ad state"><h3>Explicit confirmation required</h3><p>Target state: <strong>{preview.targetDesiredState}</strong></p><p>FAKE only. No real provider or spend. Evidence divergence blocks create or resume.</p><button type="button" onClick={onConfirm}>Confirm FAKE operation</button></section>}
