import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { PlatformMetaManager } from "./platform-meta-manager";

afterEach(()=>{cleanup();vi.unstubAllGlobals();});

describe("PlatformMetaManager",()=>{
 it("requires preview and an explicit second confirmation",async()=>{const request="11111111-1111-4111-8111-111111111111";vi.stubGlobal("crypto",{randomUUID:()=>request});const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({clientRequestUuid:request,operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",desiredState:"PAUSED",expectedCampaignPlanVersion:0,reservation:{kind:"NONE",reservedDelta:"0",accountDayRemainingAfter:"1000"},policy:{currency:"TWD",maxBatchAmount:"300",maxAccountDayAmount:"1000"},warnings:[]}),{status:200,headers:{"content-type":"application/json"}}));vi.stubGlobal("fetch",fetch);render(<PlatformMetaManager/>);expect(screen.queryByText("Confirm FAKE operation")).not.toBeInTheDocument();fireEvent.change(screen.getByLabelText("Campaign Plan UUID"),{target:{value:request}});fireEvent.click(screen.getByText("Preview paused Campaign"));await waitFor(()=>expect(screen.getByText("Confirm FAKE operation")).toBeInTheDocument());expect(fetch).toHaveBeenCalledTimes(1);});
 it("offers retry only when due and reloads the operation after stale confirmation",async()=>{const request="11111111-1111-4111-8111-111111111111",operation="22222222-2222-4222-8222-222222222222",entity="33333333-3333-4333-8333-333333333333";vi.stubGlobal("crypto",{randomUUID:()=>request});const preview={clientRequestUuid:request,operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",desiredState:"PAUSED",expectedCampaignPlanVersion:0,reservation:{kind:"NONE",reservedDelta:"0",accountDayRemainingAfter:"1000"},policy:{currency:"TWD"},warnings:[]};const failed={operationUuid:operation,operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",entityUuid:entity,status:"FAILED_RETRYABLE",attemptCount:1,reconciliationCount:0,maxAttempts:3,nextAttemptAt:"2000-01-01T00:00:00Z",createdAt:"2000-01-01T00:00:00Z",updatedAt:"2000-01-01T00:00:00Z",version:2};const fetch=vi.fn().mockResolvedValueOnce(response(preview)).mockResolvedValueOnce(response(failed,202,{etag:'W/"2"'})).mockResolvedValueOnce(response({version:0,desiredState:"PAUSED"},200,{etag:'W/"0"'})).mockResolvedValueOnce(response({code:"PLATFORM_OPERATION_STALE",message:"reload"},412)).mockResolvedValueOnce(response({...failed,status:"SUCCEEDED",version:3},200,{etag:'W/"3"'}));vi.stubGlobal("fetch",fetch);render(<PlatformMetaManager/>);fireEvent.change(screen.getByLabelText("Campaign Plan UUID"),{target:{value:request}});fireEvent.click(screen.getByText("Preview paused Campaign"));await screen.findByText("Confirm FAKE operation");fireEvent.click(screen.getByText("Confirm FAKE operation"));await screen.findByText("Retry due operation");fireEvent.click(screen.getByText("Retry due operation"));expect(fetch).toHaveBeenCalledTimes(3);fireEvent.click(screen.getByText("Confirm retry"));await waitFor(()=>expect(screen.getByText("SUCCEEDED")).toBeInTheDocument());expect(fetch).toHaveBeenCalledTimes(5);});
 it("does not expose an early retry and requires confirmation for unknown reconciliation",async()=>{const request="11111111-1111-4111-8111-111111111111",entity="33333333-3333-4333-8333-333333333333";vi.stubGlobal("crypto",{randomUUID:()=>request});const preview={clientRequestUuid:request,operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",desiredState:"PAUSED",expectedCampaignPlanVersion:0,reservation:{kind:"NONE",reservedDelta:"0",accountDayRemainingAfter:"1000"},policy:{currency:"TWD"},warnings:[]};const operation={operationUuid:"22222222-2222-4222-8222-222222222222",operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",entityUuid:entity,status:"FAILED_RETRYABLE",attemptCount:1,reconciliationCount:0,maxAttempts:3,nextAttemptAt:"2999-01-01T00:00:00Z",createdAt:"2000-01-01T00:00:00Z",updatedAt:"2000-01-01T00:00:00Z",version:2};const fetch=vi.fn().mockResolvedValueOnce(response(preview)).mockResolvedValueOnce(response(operation,202,{etag:'W/"2"'})).mockResolvedValueOnce(response({version:0,desiredState:"PAUSED"},200,{etag:'W/"0"'})).mockResolvedValueOnce(response({...operation,status:"UNKNOWN_OUTCOME",nextAttemptAt:undefined},200,{etag:'W/"3"'}));vi.stubGlobal("fetch",fetch);render(<PlatformMetaManager/>);fireEvent.change(screen.getByLabelText("Campaign Plan UUID"),{target:{value:request}});fireEvent.click(screen.getByText("Preview paused Campaign"));await screen.findByText("Confirm FAKE operation");fireEvent.click(screen.getByText("Confirm FAKE operation"));await screen.findByText(/Retry becomes available/);expect(screen.queryByText("Retry due operation")).not.toBeInTheDocument();fireEvent.click(screen.getByText("Refresh operation"));await screen.findByText("Reconcile unknown outcome");fireEvent.click(screen.getByText("Reconcile unknown outcome"));expect(screen.getByRole("dialog",{name:"Confirm reconcile"})).toBeInTheDocument();expect(fetch).toHaveBeenCalledTimes(4);});
});

function response(body:unknown,status=200,headers:Record<string,string>={}){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json",...headers}});}
