package com.aicommerce.platform.delivery.application.port;
public sealed interface PlatformReconciliationOutcome permits ReconciliationFound,ReconciliationNotFound,ReconciliationStillUnknown,ReconciliationTerminalFailure {}
