package com.aicommerce.platform.persistence;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.reset;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicReference;
import javax.sql.DataSource;

import com.aicommerce.platform.delivery.application.Stage4BException;
import com.aicommerce.platform.delivery.application.Stage4BLedgerCriticalSectionHook;
import com.aicommerce.platform.delivery.application.Stage4BTransactions;
import com.aicommerce.platform.delivery.application.Stage4BUuidSource;
import com.aicommerce.platform.delivery.domain.PlatformBudgetType;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.postgresql.PostgreSQLContainer;

@Testcontainers @SpringBootTest @ActiveProfiles("test")
class Stage4BLedgerConcurrencyIntegrationTest {
    @Container @ServiceConnection static final PostgreSQLContainer postgres=new PostgreSQLContainer("postgres:17.6-alpine3.22");
    @Autowired Stage4BTransactions transactions; @Autowired JdbcTemplate jdbc; @Autowired Stage4BUuidSource uuids; @Autowired DataSource dataSource;
    @MockitoSpyBean Stage4BLedgerCriticalSectionHook hook;
    private final AtomicReference<String> winnerGraphAtLoserBoundary=new AtomicReference<>();

    @BeforeEach void cleanLedger(){reset(hook);winnerGraphAtLoserBoundary.set(null);jdbc.execute("TRUNCATE platform_budget_reservations, platform_operation_batches, platform_account_budget_days, platform_operation_attempts, platform_operations, platform_ad_sets, platform_campaigns, campaign_plans, audit_log_changes, audit_logs RESTART IDENTITY CASCADE");}

    @Test void freshDayBelowCeilingCommitsBothSeparateParentTransactions() throws Exception {
        ConcurrentResult result=concurrentCreates("200","300",false);
        assertThat(result.first.code).isEqualTo("SUCCESS");assertThat(result.second.code).isEqualTo("SUCCESS");assertDayAndRows("500",2,2);assertThat(result.first.entity).isNotEqualTo(result.second.entity);assertSuccessGraph(result.first,new ExpectedLedger("CREATE_AD_SET","INITIAL",null,"200","200","0","200","500",2));assertSuccessGraph(result.second,new ExpectedLedger("CREATE_AD_SET","INITIAL",null,"300","300","200","500","500",2));
    }

    @Test void freshDayExactCeilingCommitsBothAfterIndependentBaseline() throws Exception {
        var results=concurrentCreates(java.util.List.of("250","250","250","250"),-1);
        assertThat(results).extracting(Result::code).containsOnly("SUCCESS");assertDayAndRows("1000",4,4);assertThat(results).extracting(Result::entity).doesNotHaveDuplicates();for(int i=0;i<results.size();i++)assertSuccessGraph(results.get(i),new ExpectedLedger("CREATE_AD_SET","INITIAL",null,"250","250",Integer.toString(i*250),Integer.toString((i+1)*250),"1000",4));
    }

    @Test void freshDayAboveCeilingHasDeterministicLoserAndCompleteRollback() throws Exception {
        String before=allRows();var results=concurrentCreates(java.util.List.of("300","300","300","300"),3);Result loser=results.get(3);
        assertThat(results.subList(0,3)).extracting(Result::code).containsOnly("SUCCESS");assertThat(loser.code).isEqualTo("PLATFORM_BUDGET_CAP_EXCEEDED");assertDayAndRows("900",3,3);for(int i=0;i<3;i++)assertSuccessGraph(results.get(i),new ExpectedLedger("CREATE_AD_SET","INITIAL",null,"300","300",Integer.toString(i*300),Integer.toString((i+1)*300),"900",3));
        assertThat(loser.entity).isEqualTo(uuids.request(loser.request,"ad-set-entity"));assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_ad_sets WHERE platform_ad_set_uuid=?",Integer.class,loser.entity)).isZero();assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_operations WHERE operation_uuid=?",Integer.class,uuids.request(loser.request,"operation"))).isZero();assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_operation_batches WHERE operation_batch_uuid=?",Integer.class,uuids.request(loser.request,"operation-batch"))).isZero();assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_budget_reservations WHERE budget_reservation_uuid=?",Integer.class,uuids.request(loser.request,"budget-reservation"))).isZero();assertThat(jdbc.queryForObject("SELECT count(*) FROM audit_logs WHERE request_id='ledger-worker-3'",Integer.class)).isZero();assertThat(jdbc.queryForObject("SELECT count(*) FROM audit_log_changes c JOIN audit_logs l ON l.audit_uuid=c.audit_uuid WHERE l.request_id='ledger-worker-3'",Integer.class)).isZero();
        assertThat(winnerGraphAtLoserBoundary.get()).isNotNull();assertThat(allRows()).isEqualTo(winnerGraphAtLoserBoundary.get());assertThat(allRows()).doesNotContain(loser.request.toString());assertThat(before).doesNotContain(loser.request.toString());
    }

    @Test void decreaseFirstDoesNotReleaseDayAndConcurrentIncreaseAdvancesExactlyOnce() throws Exception {
        UUID first=legacyAdSet("50"),second=legacyAdSet("50");assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_account_budget_days",Integer.class)).isZero();CyclicBarrier barrier=new CyclicBarrier(2);CountDownLatch decreaseCommitted=new CountDownLatch(1);
        doAnswer(invocation->{barrier.await();if(Thread.currentThread().getName().equals("increase-second"))decreaseCommitted.await();return null;}).when(hook).beforeAccountDayClaim();
        try(var decreaseExecutor=Executors.newSingleThreadExecutor(r->new Thread(r,"decrease-first"));var increaseExecutor=Executors.newSingleThreadExecutor(r->new Thread(r,"increase-second"))){Future<Result> decrease=decreaseExecutor.submit(()->{Result result=budget(first,"40","decrease-first");decreaseCommitted.countDown();return result;});Future<Result> increase=increaseExecutor.submit(()->budget(second,"100","increase-second"));Result decreased=decrease.get(),increased=increase.get();assertThat(decreased.code).isEqualTo("SUCCESS");assertThat(increased.code).isEqualTo("SUCCESS");assertSuccessGraph(decreased,new ExpectedLedger("UPDATE_BUDGET","DECREASE_NO_RELEASE","50","40","0",null,null,"50",1));assertSuccessGraph(increased,new ExpectedLedger("UPDATE_BUDGET","INCREASE","50","100","50","0","50","50",1));}
        assertThat(dayVersion()).isEqualTo(1);assertDayAndRows("50",2,1);assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_budget_reservations WHERE reservation_kind='DECREASE_NO_RELEASE' AND reserved_amount=0",Integer.class)).isEqualTo(1);
    }

    private ConcurrentResult concurrentCreates(String firstAmount,String secondAmount,boolean deterministicLoser) throws Exception {
        UUID firstCampaign=campaign(),secondCampaign=campaign(),firstRequest=UUID.randomUUID(),secondRequest=UUID.randomUUID();CyclicBarrier barrier=new CyclicBarrier(2);CountDownLatch winnerCommitted=new CountDownLatch(1);
        doAnswer(invocation->{barrier.await();if(Thread.currentThread().getName().equals("ledger-loser"))winnerCommitted.await();return null;}).when(hook).beforeAccountDayClaim();
        try(var winner=Executors.newSingleThreadExecutor(r->new Thread(r,"ledger-winner"));var loser=Executors.newSingleThreadExecutor(r->new Thread(r,"ledger-loser"))){Future<Result> one=winner.submit(()->{Result value=create(firstCampaign,firstRequest,firstAmount,"ledger-winner");winnerCommitted.countDown();return value;});Future<Result> two=loser.submit(()->create(secondCampaign,secondRequest,secondAmount,"ledger-loser"));return new ConcurrentResult(one.get(),two.get());}
    }

    private java.util.List<Result> concurrentCreates(java.util.List<String> amounts,int loserIndex) throws Exception {int count=amounts.size();var campaigns=new java.util.ArrayList<UUID>();var requests=new java.util.ArrayList<UUID>();for(int i=0;i<count;i++){campaigns.add(campaign());requests.add(UUID.randomUUID());}CyclicBarrier barrier=new CyclicBarrier(count);CountDownLatch winners=new CountDownLatch(loserIndex<0?0:count-1);CountDownLatch[] turns=new CountDownLatch[count];for(int i=0;i<count;i++)turns[i]=new CountDownLatch(i==0?0:1);doAnswer(invocation->{barrier.await();int index=Integer.parseInt(Thread.currentThread().getName().substring("ledger-worker-".length()));turns[index].await();if(index==loserIndex){winners.await();winnerGraphAtLoserBoundary.set(allRowsCommitted());}return null;}).when(hook).beforeAccountDayClaim();try(var executor=Executors.newFixedThreadPool(count,r->new Thread(r))){var futures=new java.util.ArrayList<Future<Result>>();for(int i=0;i<count;i++){final int index=i;futures.add(executor.submit(()->{Thread.currentThread().setName("ledger-worker-"+index);Result result=create(campaigns.get(index),requests.get(index),amounts.get(index),"ledger-worker-"+index);if(index!=loserIndex)winners.countDown();if(index+1<count)turns[index+1].countDown();return result;}));}var results=new java.util.ArrayList<Result>();for(var future:futures)results.add(future.get());return results;}}

    private UUID campaign(){UUID plan=UUID.randomUUID();jdbc.update("INSERT INTO campaign_plans(campaign_uuid,campaign_name,start_date,end_date,objective,platform,budget_daily,budget_total,currency) VALUES (?,'Concurrency',?,?,'OUTCOME_SALES','META',1000,1000,'TWD')",plan,LocalDate.now().plusDays(10),LocalDate.now().plusDays(20));return transactions.confirmCampaign(UUID.randomUUID(),plan,0,"concurrency-campaign").operation().getEntityUuid();}
    private UUID legacyAdSet(String amount){UUID plan=UUID.randomUUID(),campaign=UUID.randomUUID(),adSet=UUID.randomUUID(),account=UUID.fromString("00000000-0000-4000-8000-00000000005b");jdbc.update("INSERT INTO campaign_plans(campaign_uuid,campaign_name,start_date,end_date,objective,platform,budget_daily,budget_total,currency) VALUES (?,'Legacy decrease',?,?,'OUTCOME_SALES','META',100,300,'TWD')",plan,LocalDate.now().plusDays(10),LocalDate.now().plusDays(20));jdbc.update("INSERT INTO platform_campaigns(platform_campaign_uuid,campaign_uuid,platform_account_uuid,objective,desired_state,schedule_start,schedule_end,account_timezone) VALUES (?,?,?,'OUTCOME_SALES','PAUSED',current_timestamp+interval '10 days',current_timestamp+interval '20 days','Asia/Taipei')",campaign,plan,account);jdbc.update("INSERT INTO platform_ad_sets(platform_ad_set_uuid,platform_campaign_uuid,platform_account_uuid,budget_type,budget_amount,currency,schedule_start,schedule_end,account_timezone,optimization_goal,targeting_profile_key,placement_profile_key,desired_state) VALUES (?,?,?,'LIFETIME',?,'TWD',current_timestamp+interval '10 days',current_timestamp+interval '20 days','Asia/Taipei','OFFSITE_CONVERSIONS','TW_BROAD_FEEDS_V1','TW_BROAD_FEEDS_V1','PAUSED')",adSet,campaign,account,new BigDecimal(amount));return adSet;}
    private Result create(UUID campaign,UUID request,String amount,String requestId){Instant lower=dbNow();UUID candidate=uuids.request(request,"ad-set-entity");try{var value=transactions.confirmAdSet(campaign,request,PlatformBudgetType.LIFETIME,new BigDecimal(amount),0,0,requestId).operation();return new Result("SUCCESS",request,value.getEntityUuid(),requestId,lower,dbNow());}catch(Stage4BException failure){return new Result(failure.code(),request,candidate,requestId,lower,dbNow());}}
    private Result budget(UUID adSet,String amount,String requestId){UUID request=UUID.randomUUID();Instant lower=dbNow();try{var value=transactions.confirmBudget(adSet,request,new BigDecimal(amount),0,requestId).operation();return new Result("SUCCESS",request,value.getEntityUuid(),requestId,lower,dbNow());}catch(Stage4BException failure){return new Result(failure.code(),request,null,requestId,lower,dbNow());}}
    private UUID dayUuid(){return jdbc.queryForObject("SELECT account_budget_day_uuid FROM platform_account_budget_days",UUID.class);}private long dayVersion(){return jdbc.queryForObject("SELECT version FROM platform_account_budget_days",Long.class);}
    private void assertDayAndRows(String amount,int reservations,int budgetOperations){assertThat(jdbc.queryForObject("SELECT reserved_amount FROM platform_account_budget_days",BigDecimal.class)).isEqualByComparingTo(amount);assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_budget_reservations",Integer.class)).isEqualTo(reservations);assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_operation_batches WHERE reserved_amount>0",Integer.class)).isEqualTo(budgetOperations);assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_account_budget_days WHERE created_at<=updated_at AND version=(SELECT count(*) FROM platform_budget_reservations WHERE reserved_amount>0)",Integer.class)).isEqualTo(1);}
    private Instant dbNow(){return jdbc.queryForObject("SELECT statement_timestamp()",java.sql.Timestamp.class).toInstant();}
    private void assertSuccessGraph(Result result,ExpectedLedger expected){
        var operation=jdbc.queryForMap("SELECT operation_uuid,platform_account_uuid,operation_type,entity_type,coalesce(platform_campaign_uuid,platform_ad_set_uuid,platform_ad_uuid) entity_uuid,status,attempt_count,reconciliation_count,max_attempts,version,client_request_uuid,requested_actor_type,requested_actor_id,request_id,created_at,updated_at,claimed_at,completed_at,next_attempt_at,external_id,normalized_error_code,safe_provider_trace_id,outcome_evidence FROM platform_operations WHERE client_request_uuid=?",result.request);
        UUID operationUuid=(UUID)operation.get("operation_uuid");assertThat(operationUuid).isEqualTo(uuids.request(result.request,"operation"));if("CREATE_AD_SET".equals(expected.operationType))assertThat(result.entity).isEqualTo(uuids.request(result.request,"ad-set-entity"));assertThat(operation.get("operation_type")).isEqualTo(expected.operationType);assertThat(operation.get("entity_type")).isEqualTo("AD_SET");assertThat(operation.get("entity_uuid")).isEqualTo(result.entity);assertThat(operation.get("status")).isEqualTo("CREATED");assertThat(((Number)operation.get("attempt_count")).intValue()).isZero();assertThat(((Number)operation.get("reconciliation_count")).intValue()).isZero();assertThat(((Number)operation.get("max_attempts")).intValue()).isEqualTo(3);assertThat(((Number)operation.get("version")).longValue()).isZero();assertThat(operation.get("client_request_uuid")).isEqualTo(result.request);assertThat(operation.get("requested_actor_type")).isEqualTo("LOCAL_ADMIN");assertThat(operation.get("requested_actor_id")).isEqualTo("local-admin");assertThat(operation.get("request_id")).isEqualTo(result.requestId);assertThat(operation.get("claimed_at")).isNull();assertThat(operation.get("completed_at")).isNull();assertThat(operation.get("next_attempt_at")).isNull();assertThat(operation.get("external_id")).isNull();assertThat(operation.get("normalized_error_code")).isNull();assertThat(operation.get("safe_provider_trace_id")).isNull();assertThat(operation.get("outcome_evidence")).isNull();Instant operationCreated=((java.sql.Timestamp)operation.get("created_at")).toInstant(),operationUpdated=((java.sql.Timestamp)operation.get("updated_at")).toInstant();assertThat(operationCreated).isEqualTo(operationUpdated);assertThat(operationCreated).isBetween(result.lower,result.upper);
        var batch=jdbc.queryForMap("SELECT * FROM platform_operation_batches WHERE operation_uuid=?",operationUuid);UUID batchUuid=(UUID)batch.get("operation_batch_uuid");
        var reservation=jdbc.queryForMap("SELECT * FROM platform_budget_reservations WHERE operation_uuid=?",operationUuid);UUID reservationUuid=(UUID)reservation.get("budget_reservation_uuid"),dayUuid=(UUID)reservation.get("account_budget_day_uuid");
        var day=jdbc.queryForMap("SELECT * FROM platform_account_budget_days WHERE account_budget_day_uuid=?",dayUuid);
        LocalDate businessDate=((java.sql.Date)batch.get("business_date")).toLocalDate();assertThat(batchUuid).isEqualTo(uuids.request(result.request,"operation-batch"));assertThat(reservationUuid).isEqualTo(uuids.request(result.request,"budget-reservation"));assertThat(dayUuid).isEqualTo(uuids.accountDay((UUID)operation.get("platform_account_uuid"),businessDate,"TWD"));
        assertThat(batch.get("platform_account_uuid")).isEqualTo(operation.get("platform_account_uuid"));assertThat(batch.get("client_request_uuid")).isEqualTo(result.request);assertThat(batch.get("currency")).isEqualTo("TWD");assertThat(((BigDecimal)batch.get("reserved_amount"))).isEqualByComparingTo((BigDecimal)reservation.get("reserved_amount"));assertThat(((Number)batch.get("version")).longValue()).isZero();
        assertThat(reservation.get("operation_batch_uuid")).isEqualTo(batchUuid);assertThat(reservation.get("platform_account_uuid")).isEqualTo(operation.get("platform_account_uuid"));assertThat(reservation.get("platform_ad_set_uuid")).isEqualTo(result.entity);assertThat(reservation.get("reservation_kind")).isEqualTo(expected.reservationKind);if(expected.previous==null)assertThat(reservation.get("previous_budget_amount")).isNull();else assertThat((BigDecimal)reservation.get("previous_budget_amount")).isEqualByComparingTo(expected.previous);assertThat((BigDecimal)reservation.get("new_budget_amount")).isEqualByComparingTo(expected.next);assertThat((BigDecimal)reservation.get("reserved_amount")).isEqualByComparingTo(expected.reserved);assertThat(reservation.get("currency")).isEqualTo("TWD");assertThat(reservation.get("business_date")).isEqualTo(batch.get("business_date"));
        assertThat(day.get("platform_account_uuid")).isEqualTo(operation.get("platform_account_uuid"));assertThat(day.get("business_date")).isEqualTo(batch.get("business_date"));assertThat(day.get("currency")).isEqualTo("TWD");assertThat((BigDecimal)day.get("reserved_amount")).isEqualByComparingTo(expected.finalAggregate);assertThat((BigDecimal)day.get("ceiling_amount")).isEqualByComparingTo("1000");assertThat(((Number)day.get("version")).longValue()).isEqualTo(expected.finalDayVersion);Instant dayCreated=((java.sql.Timestamp)day.get("created_at")).toInstant(),dayUpdated=((java.sql.Timestamp)day.get("updated_at")).toInstant();assertThat(dayCreated).isBeforeOrEqualTo(dayUpdated);
        var adSet=jdbc.queryForMap("SELECT * FROM platform_ad_sets WHERE platform_ad_set_uuid=?",result.entity);assertThat(adSet.get("platform_account_uuid")).isEqualTo(operation.get("platform_account_uuid"));assertThat(adSet.get("budget_type")).isEqualTo("LIFETIME");String durableBudget="CREATE_AD_SET".equals(expected.operationType)?expected.next:expected.previous;assertThat((BigDecimal)adSet.get("budget_amount")).isEqualByComparingTo(durableBudget);assertThat(adSet.get("currency")).isEqualTo("TWD");assertThat(adSet.get("desired_state")).isEqualTo("PAUSED");assertThat(adSet.get("observed_state")).isNull();assertThat(adSet.get("external_id")).isNull();assertThat(((Number)adSet.get("version")).longValue()).isZero();assertThat(adSet.get("optimization_goal")).isEqualTo("OFFSITE_CONVERSIONS");assertThat(adSet.get("targeting_profile_key")).isEqualTo("TW_BROAD_FEEDS_V1");assertThat(adSet.get("placement_profile_key")).isEqualTo("TW_BROAD_FEEDS_V1");Instant entityCreated=((java.sql.Timestamp)adSet.get("created_at")).toInstant(),entityUpdated=((java.sql.Timestamp)adSet.get("updated_at")).toInstant();assertThat(entityCreated).isEqualTo(entityUpdated);if("CREATE_AD_SET".equals(expected.operationType))assertThat(entityCreated).isBetween(result.lower,result.upper);else assertThat(entityCreated).isBeforeOrEqualTo(result.lower);
        Instant batchTime=((java.sql.Timestamp)batch.get("created_at")).toInstant(),reservationTime=((java.sql.Timestamp)reservation.get("created_at")).toInstant();assertThat(batchTime).isBetween(result.lower,result.upper);assertThat(reservationTime).isBetween(result.lower,result.upper);
        assertThat(jdbc.queryForObject("SELECT count(*) FROM platform_operation_attempts WHERE operation_uuid=?",Integer.class,operationUuid)).isZero();
        var audits=jdbc.queryForList("SELECT stage4b_operation_ordinal,action,entity_type,entity_uuid,actor_type,actor_id,source,request_id,occurred_at FROM audit_logs WHERE operation_uuid=? ORDER BY stage4b_operation_ordinal",operationUuid);if("CREATE_AD_SET".equals(expected.operationType)){assertThat(audits).hasSize(5);assertThat(audits).extracting(a->a.get("entity_type")).containsExactly("PLATFORM_AD_SET","PLATFORM_OPERATION_BATCH","PLATFORM_BUDGET_RESERVATION","PLATFORM_ACCOUNT_BUDGET_DAY","PLATFORM_OPERATION");}else if("INCREASE".equals(expected.reservationKind)){assertThat(audits).extracting(a->a.get("entity_type")).containsExactly("PLATFORM_OPERATION_BATCH","PLATFORM_BUDGET_RESERVATION","PLATFORM_ACCOUNT_BUDGET_DAY","PLATFORM_OPERATION");}else{assertThat(audits).extracting(a->a.get("entity_type")).containsExactly("PLATFORM_OPERATION_BATCH","PLATFORM_BUDGET_RESERVATION","PLATFORM_OPERATION");}
        for(int i=0;i<audits.size();i++){var audit=audits.get(i);assertThat(((Number)audit.get("stage4b_operation_ordinal")).intValue()).isEqualTo(i);assertThat(audit.get("actor_type")).isEqualTo("LOCAL_ADMIN");assertThat(audit.get("actor_id")).isEqualTo("local-admin");assertThat(audit.get("source")).isEqualTo("API");assertThat(audit.get("request_id")).isEqualTo(result.requestId);assertThat(((java.sql.Timestamp)audit.get("occurred_at")).toInstant()).isBetween(result.lower.minusSeconds(2),result.upper.plusSeconds(2));String type=(String)audit.get("entity_type");UUID expectedUuid=switch(type){case "PLATFORM_OPERATION"->operationUuid;case "PLATFORM_OPERATION_BATCH"->batchUuid;case "PLATFORM_BUDGET_RESERVATION"->reservationUuid;case "PLATFORM_ACCOUNT_BUDGET_DAY"->dayUuid;case "PLATFORM_AD_SET"->result.entity;default->throw new AssertionError(type);};assertThat(audit.get("entity_uuid")).isEqualTo(expectedUuid);}
        assertTransactionAAuditChanges(operationUuid,result,expected,batchUuid,reservationUuid,dayUuid,businessDate);
    }
    private void assertTransactionAAuditChanges(UUID operation,Result result,ExpectedLedger ledger,UUID batch,UUID reservation,UUID day,LocalDate date){
        var expected=new java.util.ArrayList<ExpectedAudit>();if("CREATE_AD_SET".equals(ledger.operationType))expected.add(a("CREATE","PLATFORM_AD_SET",result.entity,c("desiredState","ENUM",null,"PAUSED")));
        var batchChanges=new java.util.ArrayList<ExpectedChange>();batchChanges.add(c("operationBatchUuid","UUID",null,batch.toString()));batchChanges.add(c("budgetReservationUuid","UUID",null,reservation.toString()));batchChanges.add(c("accountBudgetDayUuid","UUID",null,day.toString()));batchChanges.add(c("businessDate","DATE",null,date.toString()));batchChanges.add(c("reservationKind","ENUM",null,ledger.reservationKind));batchChanges.add(c("currency","STRING",null,"TWD"));batchChanges.add(c("budgetAmount","DECIMAL",scale(ledger.previous),scale(ledger.next)));batchChanges.add(c("reservedAmount","DECIMAL",null,scale(ledger.reserved)));expected.add(new ExpectedAudit("CREATE","PLATFORM_OPERATION_BATCH",batch,batchChanges));expected.add(new ExpectedAudit("CREATE","PLATFORM_BUDGET_RESERVATION",reservation,java.util.List.copyOf(batchChanges)));
        if(ledger.aggregateBefore!=null)expected.add(a("UPDATE","PLATFORM_ACCOUNT_BUDGET_DAY",day,c("operationBatchUuid","UUID",null,batch.toString()),c("budgetReservationUuid","UUID",null,reservation.toString()),c("accountBudgetDayUuid","UUID",null,day.toString()),c("businessDate","DATE",null,date.toString()),c("reservationKind","ENUM",null,ledger.reservationKind),c("currency","STRING",null,"TWD"),c("reservedAmount","DECIMAL",null,scale(ledger.reserved)),c("aggregateReservedAmount","DECIMAL",scale(ledger.aggregateBefore),scale(ledger.aggregateAfter))));expected.add(a("CREATE","PLATFORM_OPERATION",operation,c("operationStatus","ENUM",null,"CREATED")));
        var actual=jdbc.queryForList("select l.stage4b_operation_ordinal,l.action,l.entity_type,l.entity_uuid,l.actor_type,l.actor_id,l.source,l.request_id,c.change_order,c.field_name,c.value_type,c.old_value,c.new_value from audit_logs l join audit_log_changes c on c.audit_uuid=l.audit_uuid where l.operation_uuid=? order by l.stage4b_operation_ordinal,c.change_order",operation);var flat=new java.util.ArrayList<String>();for(var row:actual)flat.add(row.get("stage4b_operation_ordinal")+"|"+row.get("action")+"|"+row.get("entity_type")+"|"+row.get("entity_uuid")+"|"+row.get("actor_type")+"|"+row.get("actor_id")+"|"+row.get("source")+"|"+row.get("request_id")+"|"+row.get("change_order")+"|"+row.get("field_name")+"|"+row.get("value_type")+"|"+row.get("old_value")+"|"+row.get("new_value"));var expectedFlat=new java.util.ArrayList<String>();for(int ordinal=0;ordinal<expected.size();ordinal++){var audit=expected.get(ordinal);for(int order=0;order<audit.changes.size();order++){var change=audit.changes.get(order);expectedFlat.add(ordinal+"|"+audit.action+"|"+audit.type+"|"+audit.uuid+"|LOCAL_ADMIN|local-admin|API|"+result.requestId+"|"+order+"|"+change.field+"|"+change.type+"|"+change.oldValue+"|"+change.newValue);}}assertThat(flat).containsExactlyElementsOf(expectedFlat);
    }
    private static String scale(String value){return value==null?null:new BigDecimal(value).setScale(6).toPlainString();}private static ExpectedAudit a(String action,String type,UUID uuid,ExpectedChange...changes){return new ExpectedAudit(action,type,uuid,java.util.List.of(changes));}private static ExpectedChange c(String field,String type,String oldValue,String newValue){return new ExpectedChange(field,type,oldValue,newValue);}
    private String allRowsCommitted() throws Exception {try(var connection=dataSource.getConnection();var statement=connection.createStatement();var result=statement.executeQuery(snapshotSql())){result.next();return result.getString(1);}}
    private static String snapshotSql(){return "SELECT jsonb_build_object('operations',(SELECT jsonb_agg(to_jsonb(t) ORDER BY operation_uuid) FROM platform_operations t),'attempts',(SELECT jsonb_agg(to_jsonb(t) ORDER BY operation_attempt_uuid) FROM platform_operation_attempts t),'batches',(SELECT jsonb_agg(to_jsonb(t) ORDER BY operation_batch_uuid) FROM platform_operation_batches t),'reservations',(SELECT jsonb_agg(to_jsonb(t) ORDER BY budget_reservation_uuid) FROM platform_budget_reservations t),'days',(SELECT jsonb_agg(to_jsonb(t) ORDER BY account_budget_day_uuid) FROM platform_account_budget_days t),'campaigns',(SELECT jsonb_agg(to_jsonb(t) ORDER BY platform_campaign_uuid) FROM platform_campaigns t),'adsets',(SELECT jsonb_agg(to_jsonb(t) ORDER BY platform_ad_set_uuid) FROM platform_ad_sets t),'audit',(SELECT jsonb_agg(to_jsonb(t) ORDER BY audit_uuid) FROM audit_logs t),'changes',(SELECT jsonb_agg(to_jsonb(t) ORDER BY audit_uuid,change_order) FROM audit_log_changes t))::text";}
    private String allRows(){return jdbc.queryForObject(snapshotSql(),String.class);}
    private record Result(String code,UUID request,UUID entity,String requestId,Instant lower,Instant upper){} private record ConcurrentResult(Result first,Result second){}private record ExpectedLedger(String operationType,String reservationKind,String previous,String next,String reserved,String aggregateBefore,String aggregateAfter,String finalAggregate,long finalDayVersion){}private record ExpectedAudit(String action,String type,UUID uuid,java.util.List<ExpectedChange> changes){}private record ExpectedChange(String field,String type,String oldValue,String newValue){}
}
