package com.aicommerce.platform.delivery.domain;
import java.math.BigDecimal; import java.time.Instant; import java.util.UUID; import com.aicommerce.platform.common.persistence.MutableEntity; import jakarta.persistence.*; import org.hibernate.annotations.JdbcTypeCode; import org.hibernate.type.SqlTypes;
@Entity @Table(name="platform_ad_sets") public class PlatformAdSet extends MutableEntity {
 @Id @Column(name="platform_ad_set_uuid",updatable=false) private UUID platformAdSetUuid; @Column(name="platform_campaign_uuid",updatable=false) private UUID platformCampaignUuid; @Column(name="platform_account_uuid",updatable=false) private UUID platformAccountUuid;
 @Enumerated(EnumType.STRING) @Column(name="budget_type",updatable=false) private BudgetType budgetType; @Column(name="budget_amount",precision=19,scale=6) private BigDecimal budgetAmount; @JdbcTypeCode(SqlTypes.CHAR) @Column(name="currency",updatable=false,columnDefinition="char(3)") private String currency;
 @Column(name="schedule_start",updatable=false) private Instant scheduleStart; @Column(name="schedule_end",updatable=false) private Instant scheduleEnd; @Column(name="account_timezone",updatable=false) private String accountTimezone; @Column(name="optimization_goal",updatable=false) private String optimizationGoal; @Column(name="targeting_profile_key",updatable=false) private String targetingProfileKey; @Column(name="placement_profile_key",updatable=false) private String placementProfileKey;
 @Enumerated(EnumType.STRING) @Column(name="desired_state") private PlatformDesiredState desiredState; @Column(name="observed_state") private String observedState; @Column(name="external_id") private String externalId;
 protected PlatformAdSet(){} public UUID getPlatformAdSetUuid(){return platformAdSetUuid;} public BigDecimal getBudgetAmount(){return budgetAmount;} public PlatformDesiredState getDesiredState(){return desiredState;}
}
