package com.aicommerce.platform.delivery.application.audit;
public enum PlatformAuditSubjectType { PLATFORM_CAMPAIGN, PLATFORM_AD_SET, PLATFORM_AD, PLATFORM_OPERATION, PLATFORM_OPERATION_ATTEMPT, PLATFORM_OPERATION_BATCH, PLATFORM_BUDGET_RESERVATION, PLATFORM_ACCOUNT_BUDGET_DAY }
