package com.aicommerce.platform.delivery.application.audit;

import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;
import com.aicommerce.platform.audit.domain.AuditAction;import com.aicommerce.platform.delivery.domain.*;
public record PlatformBudgetAuditEvent(PlatformAuditSubjectType subjectType,UUID subjectUuid,AuditAction action,
 PlatformBudgetAuditEventKind eventKind,UUID operationUuid,PlatformOperationType operationType,PlatformEntityType entityType,
 UUID entityUuid,UUID operationBatchUuid,Optional<UUID> budgetReservationUuid,Optional<UUID> accountBudgetDayUuid,
 LocalDate businessDate,Optional<PlatformReservationKind> reservationKind,String currency,
 Optional<BigDecimal> previousBudgetAmount,Optional<BigDecimal> newBudgetAmount,BigDecimal reservedAmount,
 Optional<BigDecimal> previousAggregateAmount,Optional<BigDecimal> newAggregateAmount){
 public PlatformBudgetAuditEvent{Objects.requireNonNull(subjectType);Objects.requireNonNull(subjectUuid);Objects.requireNonNull(action);Objects.requireNonNull(eventKind);Objects.requireNonNull(operationUuid);Objects.requireNonNull(operationType);Objects.requireNonNull(entityType);Objects.requireNonNull(entityUuid);Objects.requireNonNull(operationBatchUuid);Objects.requireNonNull(budgetReservationUuid);Objects.requireNonNull(accountBudgetDayUuid);Objects.requireNonNull(businessDate);Objects.requireNonNull(reservationKind);Objects.requireNonNull(currency);Objects.requireNonNull(previousBudgetAmount);Objects.requireNonNull(newBudgetAmount);Objects.requireNonNull(reservedAmount);Objects.requireNonNull(previousAggregateAmount);Objects.requireNonNull(newAggregateAmount);
  boolean budgetOperation=operationType==PlatformOperationType.CREATE_AD_SET||operationType==PlatformOperationType.UPDATE_BUDGET;
  boolean operationShape=(operationType==PlatformOperationType.CREATE_CAMPAIGN&&entityType==PlatformEntityType.CAMPAIGN)||(operationType==PlatformOperationType.CREATE_AD_SET&&entityType==PlatformEntityType.AD_SET)||(Set.of(PlatformOperationType.PAUSE,PlatformOperationType.RESUME).contains(operationType)&&Set.of(PlatformEntityType.CAMPAIGN,PlatformEntityType.AD_SET).contains(entityType))||(operationType==PlatformOperationType.UPDATE_BUDGET&&entityType==PlatformEntityType.AD_SET);
  boolean amountsValid=reservedAmount.signum()>=0&&reservedAmount.scale()<=6&&previousBudgetAmount.stream().allMatch(v->v.signum()>0&&v.scale()<=6)&&newBudgetAmount.stream().allMatch(v->v.signum()>0&&v.scale()<=6)&&previousAggregateAmount.stream().allMatch(v->v.signum()>=0&&v.scale()<=6)&&newAggregateAmount.stream().allMatch(v->v.signum()>0&&v.scale()<=6);
  if(!operationShape||!"TWD".equals(currency)||!amountsValid)throw invalid();
  switch(eventKind){
   case OPERATION_BATCH_CREATED->{if(subjectType!=PlatformAuditSubjectType.PLATFORM_OPERATION_BATCH||action!=AuditAction.CREATE||!subjectUuid.equals(operationBatchUuid)||budgetOperation!=budgetReservationUuid.isPresent()||budgetOperation!=accountBudgetDayUuid.isPresent()||budgetOperation!=reservationKind.isPresent()||!previousAggregateAmount.isEmpty()||!newAggregateAmount.isEmpty())throw invalid();if(!budgetOperation&&(!previousBudgetAmount.isEmpty()||!newBudgetAmount.isEmpty()||reservedAmount.signum()!=0))throw invalid();validateReservationAmounts(operationType,reservationKind,previousBudgetAmount,newBudgetAmount,reservedAmount);}
   case BUDGET_RESERVATION_CREATED->{if(subjectType!=PlatformAuditSubjectType.PLATFORM_BUDGET_RESERVATION||action!=AuditAction.CREATE||budgetReservationUuid.isEmpty()||!subjectUuid.equals(budgetReservationUuid.orElseThrow())||accountBudgetDayUuid.isEmpty()||reservationKind.isEmpty()||!previousAggregateAmount.isEmpty()||!newAggregateAmount.isEmpty())throw invalid();validateReservationAmounts(operationType,reservationKind,previousBudgetAmount,newBudgetAmount,reservedAmount);}
   case ACCOUNT_DAY_RESERVED->{if(subjectType!=PlatformAuditSubjectType.PLATFORM_ACCOUNT_BUDGET_DAY||action!=AuditAction.UPDATE||budgetReservationUuid.isEmpty()||accountBudgetDayUuid.isEmpty()||!subjectUuid.equals(accountBudgetDayUuid.orElseThrow())||reservationKind.isEmpty()||!previousBudgetAmount.isEmpty()||!newBudgetAmount.isEmpty()||previousAggregateAmount.isEmpty()||newAggregateAmount.isEmpty()||reservedAmount.signum()<=0||newAggregateAmount.orElseThrow().compareTo(previousAggregateAmount.orElseThrow().add(reservedAmount))!=0)throw invalid();}
  }
 }
 private static void validateReservationAmounts(PlatformOperationType operationType,Optional<PlatformReservationKind> kind,Optional<BigDecimal> previous,Optional<BigDecimal> next,BigDecimal reserved){if(operationType==PlatformOperationType.CREATE_AD_SET){if(kind.orElse(null)!=PlatformReservationKind.INITIAL||previous.isPresent()||next.isEmpty()||reserved.compareTo(next.orElseThrow())!=0)throw invalid();}else if(operationType==PlatformOperationType.UPDATE_BUDGET){if(kind.isEmpty()||previous.isEmpty()||next.isEmpty())throw invalid();int direction=next.orElseThrow().compareTo(previous.orElseThrow());if(kind.orElseThrow()==PlatformReservationKind.INCREASE&&(direction<=0||reserved.compareTo(next.orElseThrow().subtract(previous.orElseThrow()))!=0))throw invalid();if(kind.orElseThrow()==PlatformReservationKind.DECREASE_NO_RELEASE&&(direction>=0||reserved.signum()!=0))throw invalid();if(kind.orElseThrow()==PlatformReservationKind.INITIAL)throw invalid();}else if(kind.isPresent()||previous.isPresent()||next.isPresent()||reserved.signum()!=0)throw invalid();}
 private static IllegalArgumentException invalid(){return new IllegalArgumentException("PLATFORM_CONTRACT_INVALID");}
}
