package com.aicommerce.platform.delivery.infrastructure.provider;
import static org.assertj.core.api.Assertions.assertThat; import java.time.Instant; import java.util.*; import org.junit.jupiter.api.Test;
import com.aicommerce.platform.delivery.application.port.*; import com.aicommerce.platform.delivery.domain.*;
class DeterministicFakePlatformAdapterTest {
 private final UUID operation=UUID.fromString("00000000-0000-0000-0000-000000000001"); private final PlatformCommandIdentity identity=new PlatformCommandIdentity(operation,UUID.randomUUID(),"a".repeat(64),"b".repeat(64));
 @Test void createIsDeterministicAndTransactionFree(){var adapter=new DeterministicFakePlatformAdapter();var command=new PlatformCampaignCommand(identity,UUID.randomUUID(),UUID.randomUUID(),PlatformObjective.OUTCOME_SALES,PlatformDesiredState.PAUSED,Optional.empty(),Optional.empty(),"Asia/Taipei");var first=(WriteSucceeded)adapter.submitCampaign(command);var second=(WriteSucceeded)adapter.submitCampaign(command);assertThat(first.externalId()).isEqualTo(second.externalId());assertThat(first.externalId().orElseThrow()).matches("fake-campaign-[0-9a-f]{24}");assertThat(adapter.transactionObserved()).isFalse();}
 @Test void mutationReturnsNoIdOrFingerprint(){var adapter=new DeterministicFakePlatformAdapter();var out=(WriteSucceeded)adapter.changeCampaignState(new PlatformStateMutationCommand(identity,PlatformEntityType.CAMPAIGN,UUID.randomUUID(),"fake-campaign-abc",0,PlatformDesiredState.ACTIVE));assertThat(out.externalId()).isEmpty();assertThat(out.evidence().externalIdFingerprint()).isEmpty();}
 @Test void allNormalizedFixturesAreStable(){assertThat(new DeterministicFakePlatformAdapter(DeterministicFakePlatformAdapter.Scenario.RETRYABLE_RATE_LIMIT).submitCampaign(command())).isInstanceOf(WriteRetryableFailure.class);assertThat(new DeterministicFakePlatformAdapter(DeterministicFakePlatformAdapter.Scenario.TERMINAL_PERMISSION).submitCampaign(command())).isInstanceOf(WriteTerminalFailure.class);assertThat(new DeterministicFakePlatformAdapter(DeterministicFakePlatformAdapter.Scenario.AMBIGUOUS_TIMEOUT).submitCampaign(command())).isInstanceOf(WriteUnknownOutcome.class);}
 private PlatformCampaignCommand command(){return new PlatformCampaignCommand(identity,UUID.randomUUID(),UUID.randomUUID(),PlatformObjective.OUTCOME_SALES,PlatformDesiredState.PAUSED,Optional.empty(),Optional.empty(),"Asia/Taipei");}
}
