import { expect, test } from "@playwright/test";

test("previews and explicitly confirms paused FAKE Campaign and Ad Set",async({page})=>{
 const campaignPlan=await page.request.post("/api/campaigns",{data:{campaignName:`Stage4B ${Date.now()}`,activityType:"SALES",startDate:"2030-01-01",endDate:"2030-01-31",objective:"OUTCOME_SALES",platform:"META",budgetDaily:100,budgetTotal:300,currency:"TWD",promotion:null,landingPage:null}});
 expect(campaignPlan.status()).toBe(201);const plan=await campaignPlan.json();
 await page.goto("/platforms/meta");await expect(page.getByRole("heading",{name:"Meta platform operations"})).toBeVisible();
 await page.getByLabel("Campaign Plan UUID").fill(plan.campaignUuid);await page.getByRole("button",{name:"Preview paused Campaign"}).click();
 await expect(page.getByRole("dialog",{name:"Confirm platform mutation"})).toContainText("PAUSED");
 await page.getByRole("button",{name:"Confirm FAKE operation"}).click();await expect(page.getByText("SUCCEEDED",{exact:true})).toBeVisible();
 const campaign=await page.getByRole("definition").nth(1).textContent();expect(campaign).toBeTruthy();
 await page.getByRole("button",{name:"Preview resume Campaign"}).click();await expect(page.getByRole("dialog",{name:"Confirm platform mutation"})).toContainText("ACTIVE");await page.getByRole("button",{name:"Confirm FAKE operation"}).click();await expect(page.getByLabel("Campaign status")).toContainText("ACTIVE");
 await page.getByRole("button",{name:"Preview paused Ad Set"}).click();await expect(page.getByRole("dialog",{name:"Confirm platform mutation"})).toContainText("TWD 50");
 await page.getByRole("button",{name:"Confirm FAKE operation"}).click();await expect(page.getByRole("dialog",{name:"Confirm platform mutation"})).toBeHidden();await expect(page.getByLabel("Ad Set status")).toContainText("PAUSED");
 await page.getByRole("button",{name:"Preview resume Ad Set"}).click();await page.getByRole("button",{name:"Confirm FAKE operation"}).click();await expect(page.getByLabel("Ad Set status")).toContainText("ACTIVE");
 await page.getByLabel("Daily budget (TWD)").fill("60");await page.getByRole("button",{name:"Preview budget change"}).click();await expect(page.getByRole("dialog",{name:"Confirm platform mutation"})).toContainText("TWD 10");await page.getByRole("button",{name:"Confirm FAKE operation"}).click();await expect(page.getByLabel("Ad Set status")).toContainText("60");
 await page.getByLabel("Daily budget (TWD)").fill("40");await page.getByRole("button",{name:"Preview budget change"}).click();await expect(page.getByText(/does not release/)).toBeVisible();await page.getByRole("button",{name:"Confirm FAKE operation"}).click();await expect(page.getByLabel("Ad Set status")).toContainText("40");
 await page.getByRole("button",{name:"Preview pause Ad Set"}).click();await page.getByRole("button",{name:"Confirm FAKE operation"}).click();await expect(page.getByLabel("Ad Set status")).toContainText("PAUSED");
});

test("enforces due retry, stale reload, unknown reconciliation, and no automatic mutation",async({page})=>{
 const plan="11111111-1111-4111-8111-111111111111",entity="22222222-2222-4222-8222-222222222222",operation="33333333-3333-4333-8333-333333333333";let operationGets=0,retries=0,reconciles=0;
 await page.route("**/api/platforms/meta/**",async route=>{const url=new URL(route.request().url());if(url.pathname.endsWith("/preview")){await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({clientRequestUuid:"44444444-4444-4444-8444-444444444444",operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",desiredState:"PAUSED",expectedCampaignPlanVersion:0,reservation:{kind:"NONE",reservedDelta:"0",accountDayRemainingAfter:"1000"},policy:{currency:"TWD"},warnings:[]})});}else if(route.request().method()==="POST"){await route.fulfill({status:202,contentType:"application/json",headers:{etag:'W/"2"'},body:JSON.stringify({operationUuid:operation,operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",entityUuid:entity,status:"FAILED_RETRYABLE",attemptCount:1,reconciliationCount:0,maxAttempts:3,nextAttemptAt:"2000-01-01T00:00:00Z",createdAt:"2000-01-01T00:00:00Z",updatedAt:"2000-01-01T00:00:00Z",version:2})});}else{await route.fulfill({status:200,contentType:"application/json",headers:{etag:'W/"0"'},body:JSON.stringify({version:0,desiredState:"PAUSED"})});}});
 await page.route("**/api/platform-operations/**",async route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith("/retry")){retries++;await route.fulfill({status:412,contentType:"application/json",body:JSON.stringify({code:"PLATFORM_OPERATION_STALE",message:"The platform operation changed; reload and retry"})});}else if(path.endsWith("/reconcile")){reconciles++;await route.fulfill({status:202,contentType:"application/json",headers:{etag:'W/"4"'},body:JSON.stringify({operationUuid:operation,operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",entityUuid:entity,status:"SUCCEEDED",attemptCount:1,reconciliationCount:1,maxAttempts:3,createdAt:"2000-01-01T00:00:00Z",updatedAt:"2000-01-01T00:00:00Z",version:4})});}else{operationGets++;await route.fulfill({status:200,contentType:"application/json",headers:{etag:'W/"3"'},body:JSON.stringify({operationUuid:operation,operationType:"CREATE_CAMPAIGN",entityType:"CAMPAIGN",entityUuid:entity,status:"UNKNOWN_OUTCOME",attemptCount:1,reconciliationCount:0,maxAttempts:3,createdAt:"2000-01-01T00:00:00Z",updatedAt:"2000-01-01T00:00:00Z",version:3})});}});
 await page.goto("/platforms/meta");await page.getByLabel("Campaign Plan UUID").fill(plan);await page.getByRole("button",{name:"Preview paused Campaign"}).click();expect(retries).toBe(0);await page.getByRole("button",{name:"Confirm FAKE operation"}).click();await page.getByRole("button",{name:"Retry due operation"}).click();expect(retries).toBe(0);await page.getByRole("button",{name:"Confirm retry"}).click();await expect(page.getByText("Reconcile unknown outcome")).toBeVisible();expect(retries).toBe(1);expect(operationGets).toBe(1);await page.getByRole("button",{name:"Reconcile unknown outcome"}).click();expect(reconciles).toBe(0);await page.getByRole("button",{name:"Confirm reconcile"}).click();await expect(page.getByText("SUCCEEDED",{exact:true})).toBeVisible();expect(reconciles).toBe(1);
});
