package com.aicommerce.platform.delivery.application;
import java.math.BigDecimal; import java.time.*; import java.util.*; import java.text.Normalizer;
import com.aicommerce.platform.audit.domain.AuditOperationContext; import com.aicommerce.platform.delivery.application.port.*; import com.aicommerce.platform.delivery.domain.*;
import org.springframework.beans.factory.ObjectProvider; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import tools.jackson.databind.ObjectMapper;
@Service public class PlatformOperationService {
 private final PlatformOperationTransactions tx; private final PlatformOperationInputCanonicalizer canonicalizer; private final PlatformOutcomeValidator outcomes; private final PlatformCampaignPort campaigns; private final PlatformAdSetPort adSets; private final PlatformAdPort ads; private final PlatformOperationReconciliationPort reconciliation; private final JdbcTemplate jdbc; private final ObjectMapper mapper; private final Clock clock;
 public PlatformOperationService(PlatformOperationTransactions tx,PlatformOperationInputCanonicalizer canonicalizer,PlatformOutcomeValidator outcomes,ObjectProvider<PlatformCampaignPort> campaigns,ObjectProvider<PlatformAdSetPort> adSets,ObjectProvider<PlatformAdPort> ads,ObjectProvider<PlatformOperationReconciliationPort> reconciliation,JdbcTemplate jdbc,ObjectMapper mapper,Clock clock){this.tx=tx;this.canonicalizer=canonicalizer;this.outcomes=outcomes;this.campaigns=campaigns.getIfAvailable();this.adSets=adSets.getIfAvailable();this.ads=ads.getIfAvailable();this.reconciliation=reconciliation.getIfAvailable();this.jdbc=jdbc;this.mapper=mapper;this.clock=clock;}
 public PlatformOperation create(CreatePlatformOperationCommand command,AuditOperationContext context){if(command==null||context==null||context.actor()==null||context.actor().id()==null||context.requestId()==null||!context.requestId().matches("^[A-Za-z0-9._:-]{1,128}$"))throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_CONTRACT_INVALID,Optional.empty());String actorId=Normalizer.normalize(context.actor().id(),Normalizer.Form.NFC);if(actorId.isBlank()||actorId.length()>128)throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_CONTRACT_INVALID,Optional.of(command.operationUuid()));AuditOperationContext normalizedContext=new AuditOperationContext(context.operationUuid(),context.requestId(),new com.aicommerce.platform.audit.domain.AuditActor(context.actor().type(),actorId),context.source());PlatformOperationInputCanonicalizer.CanonicalInput input;try{input=command.operationType()==PlatformOperationType.CREATE_AD?canonicalizer.canonicalizeNewCreateAd(command.normalizedRequestJson()):canonicalizer.canonicalize(command.normalizedRequestJson());}catch(RuntimeException exception){throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_CONTRACT_INVALID,Optional.of(command.operationUuid()));}Boolean valid=jdbc.queryForObject("SELECT is_valid_platform_request(?::jsonb,?,?,?)",Boolean.class,input.json(),command.operationType().name(),command.entityType().name(),command.entityUuid());if(!Boolean.TRUE.equals(valid))throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_CONTRACT_INVALID,Optional.of(command.operationUuid()));String identity="platform-operation-v1\n"+command.platformAccountUuid().toString().toLowerCase()+"\n"+normalizedContext.actor().type()+"\n"+actorId+"\n"+command.clientRequestUuid().toString().toLowerCase();return tx.createOrReplay(command,input,canonicalizer.idempotencyKey(identity),normalizedContext);}
 public PlatformOperationView submit(UUID operationUuid,long expectedOperationVersion){return submit(operationUuid,expectedOperationVersion,null);}
 public PlatformOperationView retry(UUID operationUuid,long expectedOperationVersion,Instant now){Objects.requireNonNull(now);return submitAt(operationUuid,expectedOperationVersion,now,tx.operationContext(operationUuid),true);}
 public PlatformOperationView submit(UUID operationUuid,long expectedOperationVersion,AuditOperationContext context){return submitAt(operationUuid,expectedOperationVersion,Instant.now(clock),context==null?tx.operationContext(operationUuid):context,false);}
 private PlatformOperationView submitAt(UUID operationUuid,long expectedOperationVersion,Instant now,AuditOperationContext context,boolean retry){requireAdapter(operationUuid);AuditOperationContext c=requireContext(context);PlatformCommand generic=retry?tx.claimRetry(operationUuid,expectedOperationVersion,now,c):tx.claimSubmit(operationUuid,expectedOperationVersion,now,c);PlatformWriteOutcome outcome;try{outcome=outcomes.validateWrite(generic.operationType(),generic.durableEntityExternalId(),dispatch(generic));}catch(RuntimeException ex){outcome=unknown();}try{return view(tx.recordWriteOutcome(operationUuid,outcome,c));}catch(org.springframework.dao.DataAccessException ex){if(recoverableAdDispatch(ex,generic)){try{return view(tx.recoverImmediateAmbiguity(operationUuid,traceOf(outcome),c));}catch(RuntimeException recovery){throw recovery;}}throw ex;}}
 public PlatformOperation execute(UUID operationUuid,long expectedVersion,AuditOperationContext context){submit(operationUuid,expectedVersion,context);return tx.get(operationUuid);}
 public PlatformOperationView reconcile(UUID operationUuid,long expectedOperationVersion){requireAdapter(operationUuid);AuditOperationContext c=tx.operationContext(operationUuid);var query=tx.claimReconciliation(operationUuid,expectedOperationVersion,Instant.now(clock),c);PlatformReconciliationOutcome outcome;try{outcome=outcomes.validateReconciliation(query.operationType(),query.knownExternalId(),reconciliation.reconcile(query));}catch(RuntimeException ex){outcome=reconciliationUnknown();}try{return view(tx.recordReconciliationOutcome(operationUuid,outcome,Instant.now(clock),c));}catch(org.springframework.dao.DataAccessException ex){if(recoverableAdDispatch(ex,query.operationType(),query.entityType())){try{return view(tx.recoverImmediateAmbiguity(operationUuid,traceOf(outcome),c));}catch(RuntimeException recovery){throw recovery;}}throw ex;}}
 public PlatformOperation reconcile(UUID operationUuid,AuditOperationContext context){PlatformOperation current=tx.get(operationUuid);reconcile(operationUuid,current.getVersion());return tx.get(operationUuid);}
 public PlatformOperationView recoverStaleClaim(UUID operationUuid,long expectedOperationVersion,Instant recoveryTime){Objects.requireNonNull(recoveryTime);return view(tx.recoverStaleClaim(operationUuid,expectedOperationVersion,recoveryTime,tx.operationContext(operationUuid)));}
 public PlatformOperation recoverExpiredSubmission(UUID operationUuid,long expectedVersion,AuditOperationContext context){return tx.recoverStaleClaim(operationUuid,expectedVersion,Instant.now(clock),context==null?tx.operationContext(operationUuid):context);}
 private PlatformWriteOutcome dispatch(PlatformCommand c){Map<String,Object> p=payload(c.normalizedRequestJson());PlatformCommandIdentity i=new PlatformCommandIdentity(c.operationUuid(),c.accountUuid(),idempotency(c.operationUuid()),c.requestSha256());return switch(c.operationType()){
  case CREATE_CAMPAIGN->campaigns.submitCampaign(new PlatformCampaignCommand(i,c.entityUuid(),uuid(p,"campaignUuid"),PlatformObjective.OUTCOME_SALES,PlatformDesiredState.PAUSED,instant(p,"scheduleStart"),instant(p,"scheduleEnd"),text(p,"accountTimezone","Asia/Taipei")));
  case CREATE_AD_SET->adSets.submitAdSet(new PlatformAdSetCommand(i,c.entityUuid(),uuid(p,"platformCampaignUuid"),PlatformBudgetType.valueOf(text(p,"budgetType","DAILY")),decimal(p,"budgetAmount"),text(p,"currency","TWD"),instant(p,"scheduleStart"),instant(p,"scheduleEnd"),text(p,"accountTimezone","Asia/Taipei"),text(p,"optimizationGoal","OFFSITE_CONVERSIONS"),text(p,"targetingProfileKey","TW_BROAD_FEEDS_V1"),text(p,"placementProfileKey","TW_BROAD_FEEDS_V1"),PlatformDesiredState.PAUSED));
  case CREATE_AD->{String mapping=text(p,"creativeMappingKey",null);if(!"APPROVED_IMAGE_ASSET_V1".equals(mapping))throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_CONTRACT_INVALID,Optional.of(c.operationUuid()));yield ads.submitAd(new PlatformAdCommand(i,c.entityUuid(),uuid(p,"platformAdSetUuid"),uuid(p,"productUuid"),uuid(p,"assetUuid"),uuid(p,"generationOutputUuid"),uuid(p,"reviewDecisionUuid"),text(p,"approvedChecksumSha256",null),mapping,PlatformDesiredState.PAUSED));}
  case PAUSE,RESUME->{String external=c.durableEntityExternalId().orElseThrow();var m=new PlatformStateMutationCommand(i,c.entityType(),c.entityUuid(),external,longValue(p,"expectedEntityVersion"),c.operationType()==PlatformOperationType.PAUSE?PlatformDesiredState.PAUSED:PlatformDesiredState.ACTIVE);yield switch(c.entityType()){case CAMPAIGN->campaigns.changeCampaignState(m);case AD_SET->adSets.changeAdSetState(m);case AD->ads.changeAdState(m);};}
  case UPDATE_BUDGET->adSets.updateAdSetBudget(new PlatformBudgetMutationCommand(i,c.entityUuid(),c.durableEntityExternalId().orElseThrow(),longValue(p,"expectedEntityVersion"),PlatformBudgetType.valueOf(text(p,"budgetType","DAILY")),text(p,"currency","TWD"),decimal(p,"previousBudgetAmount"),decimal(p,"newBudgetAmount")));
 };}
 private void requireAdapter(UUID id){if(campaigns==null||adSets==null||ads==null||reconciliation==null)throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_ADAPTER_UNAVAILABLE,Optional.of(id));}
 private AuditOperationContext requireContext(AuditOperationContext c){if(c==null)throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_CONTRACT_INVALID,Optional.empty());return c;}
 @SuppressWarnings("unchecked") private Map<String,Object> payload(String json){try{return mapper.readValue(json,Map.class);}catch(Exception e){throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_CONTRACT_INVALID,Optional.empty());}}
 private String idempotency(UUID id){return jdbc.queryForObject("SELECT idempotency_key FROM platform_operations WHERE operation_uuid=?",String.class,id);}
 private static UUID uuid(Map<String,Object> p,String k){return UUID.fromString(text(p,k,null));} private static String text(Map<String,Object> p,String k,String d){Object v=p.get(k);if(v==null){if(d!=null)return d;throw new IllegalArgumentException("PLATFORM_CONTRACT_INVALID");}return v.toString();} private static BigDecimal decimal(Map<String,Object> p,String k){return new BigDecimal(text(p,k,null));} private static long longValue(Map<String,Object> p,String k){return Long.parseLong(text(p,k,null));} private static Optional<Instant> instant(Map<String,Object> p,String k){Object v=p.get(k);return v==null?Optional.empty():Optional.of(Instant.parse(v.toString()));}
 private static WriteUnknownOutcome unknown(){return new WriteUnknownOutcome(PlatformUnknownCode.PLATFORM_RESPONSE_AMBIGUOUS,Optional.empty(),new NormalizedPlatformEvidence(1,ProviderKey.FAKE,PlatformAttemptKind.SUBMIT,PlatformEvidenceResultKind.UNKNOWN_OUTCOME,Optional.empty(),Optional.empty(),Optional.empty()));}
 private static ReconciliationStillUnknown reconciliationUnknown(){return new ReconciliationStillUnknown(Optional.empty(),new NormalizedPlatformEvidence(1,ProviderKey.FAKE,PlatformAttemptKind.RECONCILE,PlatformEvidenceResultKind.STILL_UNKNOWN,Optional.empty(),Optional.empty(),Optional.empty()));}
 private static boolean recoverableAdDispatch(org.springframework.dao.DataAccessException ex,PlatformCommand command){return recoverableAdDispatch(ex,command.operationType(),command.entityType());}
 private static boolean recoverableAdDispatch(org.springframework.dao.DataAccessException ex,PlatformOperationType type,PlatformEntityType entity){if(entity!=PlatformEntityType.AD)return false;Throwable cause=ex.getMostSpecificCause();String state=cause instanceof java.sql.SQLException sql?sql.getSQLState():null;String message=cause.getMessage()==null?"":cause.getMessage();return "40001".equals(state)||"40P01".equals(state)||("23514".equals(state)&&message.contains("ct_platform_ad_dispatch_result"));}
 private static Optional<String> traceOf(PlatformWriteOutcome outcome){if(outcome instanceof WriteSucceeded x)return x.safeProviderTraceId();if(outcome instanceof WriteRetryableFailure x)return x.safeProviderTraceId();if(outcome instanceof WriteTerminalFailure x)return x.safeProviderTraceId();if(outcome instanceof WriteUnknownOutcome x)return x.safeProviderTraceId();return Optional.empty();}
 private static Optional<String> traceOf(PlatformReconciliationOutcome outcome){if(outcome instanceof ReconciliationFound x)return x.safeProviderTraceId();if(outcome instanceof ReconciliationNotFound x)return x.safeProviderTraceId();if(outcome instanceof ReconciliationStillUnknown x)return x.safeProviderTraceId();if(outcome instanceof ReconciliationTerminalFailure x)return x.safeProviderTraceId();return Optional.empty();}
 private PlatformOperationView view(PlatformOperation o){return new PlatformOperationView(o.getOperationUuid(),o.getPlatformAccountUuid(),o.getOperationType(),o.getEntityType(),o.getEntityUuid(),o.getStatus(),o.getAttemptCount(),o.getReconciliationCount(),o.getMaxAttempts(),Optional.ofNullable(o.getExternalId()),o.getNormalizedErrorCode()==null?Optional.empty():Optional.of(PlatformStableErrorCode.valueOf(o.getNormalizedErrorCode())),Optional.ofNullable(o.getSafeProviderTraceId()),evidence(o.getOutcomeEvidence()),Optional.ofNullable(o.getNextAttemptAt()),Optional.ofNullable(o.getClaimedAt()),Optional.ofNullable(o.getCompletedAt()),o.getCreatedAt(),o.getUpdatedAt(),o.getVersion());}
 @SuppressWarnings("unchecked") private Optional<NormalizedPlatformEvidence> evidence(String json){if(json==null)return Optional.empty();try{Map<String,Object> p=mapper.readValue(json,Map.class);return Optional.of(new NormalizedPlatformEvidence(((Number)p.get("schemaVersion")).intValue(),ProviderKey.valueOf(p.get("providerKey").toString()),PlatformAttemptKind.valueOf(p.get("attemptKind").toString()),PlatformEvidenceResultKind.valueOf(p.get("resultKind").toString()),Optional.ofNullable((String)p.get("externalIdFingerprint")),Optional.ofNullable((String)p.get("observedState")).map(PlatformObservedState::valueOf),Optional.ofNullable((Number)p.get("retryAfterSeconds")).map(Number::intValue)));}catch(RuntimeException ex){throw new PlatformOperationException(PlatformStableErrorCode.PLATFORM_EVIDENCE_INVALID,Optional.empty());}}
}
