import { NextRequest } from "next/server";
import { afterEach, describe, expect, it, vi } from "vitest";
import { forwardStage4B } from "./platform-stage4b";

afterEach(()=>{vi.unstubAllGlobals();delete process.env.PLATFORM_STAGE4B_ENABLED;delete process.env.BACKEND_INTERNAL_URL;});
describe("Stage 4B fail-closed proxy",()=>{
 it("returns a local 404 while disabled without contacting Backend",async()=>{const fetch=vi.fn();vi.stubGlobal("fetch",fetch);const result=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns/preview",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),"/api/platforms/meta/campaigns/preview");expect(result.status).toBe(404);expect(fetch).not.toHaveBeenCalled();});
 it("forwards only the fixed path and safe headers",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const fetch=vi.fn().mockResolvedValue(new Response('{"status":"SUCCEEDED"}',{status:202,headers:{ETag:'W/"2"',Location:"/api/platform-operations/a"}}));vi.stubGlobal("fetch",fetch);const request=new NextRequest("http://local/api/platforms/meta/campaigns",{method:"POST",headers:{"content-type":"application/json","x-request-id":"safe-1",authorization:"secret"},body:'{"clientRequestUuid":"x"}'});const result=await forwardStage4B(request,"/api/platforms/meta/campaigns");expect(result.status).toBe(202);const init=fetch.mock.calls[0][1];expect(init.headers.get("Authorization")).toBeNull();expect(init.headers.get("X-Request-ID")).toBe("safe-1");expect(init.redirect).toBe("manual");});
 it("rejects query strings and oversized bodies locally",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const query=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns?account=forbidden"),"/api/platforms/meta/campaigns");expect(query.status).toBe(400);const large=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:"x".repeat(16385)}),"/api/platforms/meta/campaigns");expect(large.status).toBe(413);});
 it("fails closed for redirect, empty, invalid, forbidden, and oversized Backend responses",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const request=new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");for(const response of [new Response(null,{status:302}),new Response(""),new Response("not-json"),new Response('{"externalId":"secret"}'),new Response(JSON.stringify({value:"x".repeat(1024*1024)}))]){vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response));const result=await forwardStage4B(request,"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(result.status).toBe(502);}});
 it("maps network/reset failures and rejects bodies on empty routes",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new TypeError("socket secret")));const network=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001"),"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(network.status).toBe(502);expect(await network.text()).not.toContain("socket secret");const body=await forwardStage4B(new NextRequest("http://local/api/platform-operations/00000000-0000-4000-8000-000000000001/retry",{method:"POST",body:"x"}),"/api/platform-operations/00000000-0000-4000-8000-000000000001/retry");expect(body.status).toBe(400);});
 it("composes the client abort signal into the Backend fetch",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const controller=new AbortController();const fetch=vi.fn().mockImplementation(async(_url,init)=>{controller.abort();expect(init.signal).toBeInstanceOf(AbortSignal);throw new DOMException("aborted","AbortError");});vi.stubGlobal("fetch",fetch);const result=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001",{signal:controller.signal}),"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(result.status).toBe(502);});
});
