import { NextRequest } from "next/server";
import { afterEach, describe, expect, it, vi } from "vitest";
import { forwardStage4B } from "./platform-stage4b";

afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks();delete process.env.PLATFORM_STAGE4B_ENABLED;delete process.env.PLATFORM_STAGE4C_ENABLED;delete process.env.BACKEND_INTERNAL_URL;});
describe("Stage 4B fail-closed proxy",()=>{
 it("returns a local 404 while disabled without contacting Backend",async()=>{const fetch=vi.fn();vi.stubGlobal("fetch",fetch);const result=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns/preview",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),"/api/platforms/meta/campaigns/preview");expect(result.status).toBe(404);expect(fetch).not.toHaveBeenCalled();});
 it("forwards only the fixed path and safe headers",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const fetch=vi.fn().mockResolvedValue(jsonResponse('{"status":"SUCCEEDED"}',202,{ETag:'W/"2"',Location:"/api/platform-operations/a"}));vi.stubGlobal("fetch",fetch);const request=new NextRequest("http://local/api/platforms/meta/campaigns",{method:"POST",headers:{"content-type":"application/json","x-request-id":"safe-1",authorization:"secret"},body:'{"clientRequestUuid":"x"}'});const result=await forwardStage4B(request,"/api/platforms/meta/campaigns");expect(result.status).toBe(202);const init=fetch.mock.calls[0][1];expect(init.headers.get("Authorization")).toBeNull();expect(init.headers.get("X-Request-ID")).toBe("safe-1");expect(init.redirect).toBe("manual");});
 it("allows the normalized Ad Set read route",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";vi.stubGlobal("fetch",vi.fn().mockResolvedValue(jsonResponse('{"version":1,"desiredState":"PAUSED","budgetAmount":"50"}')));const id="11111111-1111-4111-8111-111111111111";const result=await forwardStage4B(new NextRequest(`http://local/api/platforms/meta/ad-sets/${id}`),`/api/platforms/meta/ad-sets/${id}`);expect(result.status).toBe(200);});
 it("404s Ad routes unless Stage 4C is enabled and forwards them when it is",async()=>{
  const id="11111111-1111-4111-8111-111111111111";
  process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";
  const fetch=vi.fn();vi.stubGlobal("fetch",fetch);
  const disabled=await forwardStage4B(new NextRequest(`http://local/api/platforms/meta/ads/${id}`),`/api/platforms/meta/ads/${id}`);
  expect(disabled.status).toBe(404);expect(fetch).not.toHaveBeenCalled();
  process.env.PLATFORM_STAGE4C_ENABLED="true";
  const body='{"platformAdUuid":"'+id+'","desiredState":"PAUSED","creativeMappingKey":"APPROVED_IMAGE_ASSET_V1","evidenceEligible":true}';
  vi.stubGlobal("fetch",vi.fn().mockImplementation(()=>jsonResponse(body)));
  const enabled=await forwardStage4B(new NextRequest(`http://local/api/platforms/meta/ads/${id}`),`/api/platforms/meta/ads/${id}`);
  expect(enabled.status).toBe(200);
  const preview=await forwardStage4B(new NextRequest(`http://local/api/platforms/meta/ad-sets/${id}/ads/preview`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"}),`/api/platforms/meta/ad-sets/${id}/ads/preview`);
  expect(preview.status).toBe(200);
  expect(await preview.json()).toEqual({platformAdUuid:id,desiredState:"PAUSED",creativeMappingKey:"APPROVED_IMAGE_ASSET_V1",evidenceEligible:true});
 });
 it("rejects query strings and oversized bodies locally",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const query=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns?account=forbidden"),"/api/platforms/meta/campaigns");expect(query.status).toBe(400);const large=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:"x".repeat(16385)}),"/api/platforms/meta/campaigns");expect(large.status).toBe(413);});
 it("fails closed for redirect, empty, invalid, forbidden, and oversized Backend responses",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const request=new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");for(const response of [new Response(null,{status:302}),jsonResponse(""),jsonResponse("not-json"),jsonResponse('{"externalId":"secret"}'),jsonResponse(JSON.stringify({value:"x".repeat(1024*1024)}))]){vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response));const result=await forwardStage4B(request,"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(result.status).toBe(502);}});
 it("maps network/reset failures and rejects bodies on empty routes",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new TypeError("socket secret")));const network=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001"),"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(network.status).toBe(502);expect(await network.text()).not.toContain("socket secret");const body=await forwardStage4B(new NextRequest("http://local/api/platform-operations/00000000-0000-4000-8000-000000000001/retry",{method:"POST",body:"x"}),"/api/platform-operations/00000000-0000-4000-8000-000000000001/retry");expect(body.status).toBe(400);});
 it("composes the client abort signal into the Backend fetch",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const controller=new AbortController();const fetch=vi.fn().mockImplementation(async(_url,init)=>{controller.abort();expect(init.signal).toBeInstanceOf(AbortSignal);throw new DOMException("aborted","AbortError");});vi.stubGlobal("fetch",fetch);const result=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001",{signal:controller.signal}),"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(result.status).toBe(502);});
 it("aborts at exactly ten seconds and maps the timeout to 504",async()=>{vi.useFakeTimers();process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const timeout=vi.spyOn(AbortSignal,"timeout").mockImplementation(milliseconds=>{const controller=new AbortController();setTimeout(()=>controller.abort(new DOMException("timed out","TimeoutError")),milliseconds);return controller.signal;});const fetch=vi.fn().mockImplementation((_url,init)=>new Promise((_resolve,reject)=>init.signal.addEventListener("abort",()=>reject(init.signal.reason),{once:true})));vi.stubGlobal("fetch",fetch);const pending=forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001"),"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");await vi.advanceTimersByTimeAsync(9_999);expect(fetch).toHaveBeenCalledTimes(1);expect(timeout).toHaveBeenCalledWith(10_000);await vi.advanceTimersByTimeAsync(1);const result=await pending;expect(result.status).toBe(504);expect(await result.json()).toEqual({code:"BACKEND_TIMEOUT",message:"Backend request timed out"});});
 it("accepts exact request and response limits and rejects one byte over",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const exactResponse=`{"status":"${"x".repeat(1024*1024-13)}"}`;const fetch=vi.fn().mockResolvedValue(jsonResponse(exactResponse));vi.stubGlobal("fetch",fetch);const exactBody="x".repeat(16*1024);const accepted=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:exactBody}),"/api/platforms/meta/campaigns");expect(accepted.status).toBe(200);expect((fetch.mock.calls[0][1].body as Uint8Array).byteLength).toBe(16*1024);const tooLarge=await forwardStage4B(new NextRequest("http://local/api/platforms/meta/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:"x".repeat(16*1024+1)}),"/api/platforms/meta/campaigns");expect(tooLarge.status).toBe(413);});
 it("rejects extra keys, operation, replay, and outcomeEvidence as a 502 even when they miss the denylist regex",async()=>{
  process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";
  const request=new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");
  for(const body of ['{"extra":"x"}','{"operation":{}}','{"replay":true}','{"outcomeEvidence":{}}','{"value":"x"}']){
    vi.stubGlobal("fetch",vi.fn().mockResolvedValue(jsonResponse(body)));
    const result=await forwardStage4B(request,"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");
    expect(result.status,body).toBe(502);
  }
 });
 it("cancels an exact one-megabyte-plus-one streaming response",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";let cancelled=false;const stream=new ReadableStream<Uint8Array>({start(controller){controller.enqueue(new Uint8Array(1024*1024));controller.enqueue(new Uint8Array(1));},cancel(){cancelled=true;}});vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response(stream,{headers:{"content-type":"application/json"}})));const request=new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");const result=await forwardStage4B(request,"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(result.status).toBe(502);expect(cancelled).toBe(true);expect(await result.json()).toEqual({code:"BACKEND_RESPONSE_TOO_LARGE",message:"Backend response is too large"});});
 it("rejects wrong Backend content type, strips unsafe headers, and closes forbidden DTO fields",async()=>{process.env.PLATFORM_STAGE4B_ENABLED="true";process.env.BACKEND_INTERNAL_URL="http://backend:8080";const request=new NextRequest("http://local/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response("{}",{headers:{"content-type":"text/plain","set-cookie":"secret=1"}})));expect((await forwardStage4B(request,"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001")).status).toBe(502);for(const field of ["platformAccountUuid","accountReference","externalId","canonicalPayload","requestPayload","outcomeEvidence","safeProviderTraceId","authorization","cookie","token","credential","secret","providerBody","providerUrl"]){vi.stubGlobal("fetch",vi.fn().mockResolvedValue(jsonResponse(JSON.stringify({[field]:"sentinel"}))));const result=await forwardStage4B(request,"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(result.status,field).toBe(502);expect(await result.text()).not.toContain("sentinel");}vi.stubGlobal("fetch",vi.fn().mockResolvedValue(jsonResponse("{}",200,{"set-cookie":"sentinel","x-internal-secret":"sentinel",ETag:'W/"1"'})));const safe=await forwardStage4B(request,"/api/platforms/meta/campaigns/00000000-0000-4000-8000-000000000001");expect(safe.status).toBe(200);expect(safe.headers.get("set-cookie")).toBeNull();expect(safe.headers.get("x-internal-secret")).toBeNull();expect(safe.headers.get("etag")).toBe('W/"1"');});
});

function jsonResponse(body:string,status=200,headers:Record<string,string>={}){return new Response(body,{status,headers:{"content-type":"application/json",...headers}});}
